/*! ver:1419842093 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var k=void 0,l=!0,r=null,v=!1,E=window.BAIDU_DUP_require,G=window.BAIDU_DUP_define;
G&&G("union/common/oo1419842093",[],function(){function g(b){var f=g.create(g);return b.call(f,f,f.tb)}function i(b,f){if(b.constructor===Array)for(var d=0,a=b.length;d<a;d++){if(f.call(b,b[d],d,b)===v)return v}else{var d=!{toString:1}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(a in b)if(b.hasOwnProperty(a)&&f.call(b,b[a],a,b)===v)return v;if(d){d=0;for(a=c.length;d<a;d++){var e=c[d];if(b.hasOwnProperty(e)&&
f.call(b,e,d,b)===v)return v}}}return l}function e(b,f,d){i(f,function(a,c){if(!b.hasOwnProperty(c)||d)b[c]=a})}function j(b){function f(){}if(Object.create)return Object.create(b);f.prototype=b;return new f}g.tb={};g.create=j;g.bc=i;g.Oa=function(b){var f,d=b.hasOwnProperty("constructor")?b.constructor:function(){};d.prototype=b;d.prototype.constructor=d;f=f||{};f.lb&&e(d,f.lb);return d};g.extend=function(b,f,d){var a;a=f.hasOwnProperty("constructor")?f.constructor:function(){b.constructor.apply(this,
arguments)};a.prototype=j(b.prototype);e(a.prototype,f,l);a.prototype.constructor=a;a.prototype.Qc=b.prototype;e(a,b);d=d||{};d.lb&&e(a,d.lb,l);return a};g.gd=function(b){var f=this.tb;i(b.split("."),function(b){f.hasOwnProperty(b)||(f[b]={});f=f[b]});return f};g.i=function(b,f){var d;return function(){d=d||[];for(var a=0,c=arguments.length;a<c;a++)d.push(arguments[a]);return b.apply(f||{},d)}};return g});
G&&G("union/common/cookie1419842093",[],function(){return{X:function(g,i){var e,j=RegExp("(^| )"+g+"=([^;]*)(;|$)").exec((i||window).document.cookie);j&&(e=j[2]);return e},ha:function(g,i,e){var e=e||{},j=e.ba;"number"==typeof e.ba&&(j=new Date,j.setTime(j.getTime()+e.ba));document.cookie=""+g+"="+i+(e.path?"; path="+e.path:"")+(j?"; expires="+j.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.ld?"; secure":"")},remove:function(g){var i=new Date;i.setTime(i.getTime()-86400);this.ha(g,"",{path:"/",ba:i})}}});
G&&G("union/common/bom1419842093",[],function(){var g={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(g.g=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Xc=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(g.kd=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Tc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.ed)&&
(g.fd=+RegExp.$1)}catch(i){}g.Fb=/webkit/i.test(navigator.userAgent);g.tc=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);g.Eb="CSS1Compat"==document.compatMode;return{h:g,B:function(){var e=l;if(this.h.g&&(7>this.h.g||"BackCompat"===document.compatMode))e=v;return e},$c:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(g){return 0}},Zc:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(g){return 0}},D:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(g){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(g){return 0}},F:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},$a:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},Gb:function(e){var g=v;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(g=l)}catch(b){g=v}return g},ra:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.Gb(e)},Fa:function(e,g){for(var g=2===arguments.length?g:e.parent,b=0;10>b++&&this.ra(e,g);){var f;try{f=!!e.parent.location.toString()}catch(d){f=v}if(!f)return l;e=e.parent}return 10<=b?l:
v},Ec:function(e,g){var b=new Image,f="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),g=g||window;g[f]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=r;b=g[f]=r};b.src=e},Ya:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},ab:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ya(e);return e.parentWindow||e.defaultView||r},bd:function(e){e=e||window;return this.ra(e)&&
!this.Fa(e,e.top)&&this.Gb(e.top)?e.top:e}}});
G&&G("union/common/dom1419842093",["union/common/oo1419842093","union/common/bom1419842093"],function(g,i){return g(function(e){var g=i.h;return{m:function(b,f){return"string"===typeof b||b instanceof String?(f||window).document.getElementById(b):b},Db:function(b,f){var d=l;if("string"===typeof f)return b.id===f;if(f.constructor===Object)return e.bc(f,function(a,c){var f=(b.getAttribute?b.getAttribute(c):b[c])||b[c];if("tagName"===c){if(f.toUpperCase()!=a.toUpperCase())return d=v}else if(f!=a)return d=v}),d;if(f.constructor===
Array){var a=f.concat([]);a.reverse();for(var c=b;c&&a.length;c=c.parentNode)this.Db(c,a[0])&&a.shift();return!a.length?l:v}},Nb:function(b,f){if(b&&f(b)!==v){var d=b.childNodes;if(d)for(var a=0,c=d.length;a<c;a++)if(this.Nb(d[a],f)===v)return v}},Kb:function(b,f){var d=this;b.constructor===Object&&(b=this.r(b));if("string"===typeof f){for(var a=document.getElementById(f),c=a;c;){if(c===b)return a;c=c.parentNode}return r}if(f.constructor===Object){var e=r;d.Nb(b,function(a){if(d.Db(a,f))return e=
a,v});return e}},r:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.Kb(document.documentElement,b);if(b.constructor===Array){for(var f=b.concat([]),d=document.documentElement;f.length&&d;)d=this.Kb(d,f.shift());return d}}},Cc:function(b,f,d){var d=d||this.pd||window,a=d.document;this.xb=0;this.ea=this.ea||[];this.ea.push({Xa:b,wb:f||0,Ta:v});var c=
e.i(function(){var c=v;this.xb++;var b=v;try{d.frameElement&&(b=l)}catch(f){b=l}if(g.g&&9>g.g&&!b)try{a.documentElement.doScroll("left"),c=l}catch(e){}else if("complete"===a.readyState||this.ac)c=l;else if(3E5<this.xb){this.W&&(d.clearInterval(this.W),this.W=r);return}if(c)try{if(this.ea&&this.ea.length)for(var c=0,i=this.ea.length;c<i;c++){var s=this.ea[c];s&&s.Xa&&!s.Ta&&(s.wb?(s.Ta=l,d.setTimeout(s.Xa,s.wb)):(s.Ta=l,s.Xa()))}}catch(m){throw m;}finally{this.W&&(d.clearInterval(this.W),this.W=r)}},
this),b=e.i(function(){this.ac=l;c()},this);this.W||(this.W=d.setInterval(c,50),a.addEventListener?(a.addEventListener("DOMContentLoaded",b,v),d.addEventListener("load",b,v)):a.attachEvent&&d.attachEvent("onload",b,v))},B:function(){var b=l;if(g.g&&(7>g.g||"BackCompat"===document.compatMode))b=v;return b},bind:function(b,f,d){"string"===typeof b&&(b=this.r(b));f=f.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(f,d,v):b.attachEvent&&b.attachEvent("on"+f,d);return b},Ob:function(b,
f,d){b=this.r(b);if(!b)return r;f=f.replace(/^on/i,"").toLowerCase();b.removeEventListener?b.removeEventListener(f,d,v):b.detachEvent&&b.detachEvent("on"+f,d);return b},t:function(b,f){var d;"string"===typeof b&&(b=this.r(b));var a=i.Ya(b),c="",c=-1<f.indexOf("-")?f.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):f.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});a&&a.defaultView&&a.defaultView.getComputedStyle?((a=a.defaultView.getComputedStyle(b,r))&&
(d=a.getPropertyValue(f)),"boolean"!==typeof d&&!d&&(d=a.getPropertyValue(c))):b.currentStyle&&((a=b.currentStyle)&&(d=a[f]),"boolean"!==typeof d&&!d&&(d=a[c]));return d},oc:function(b,f){f=f||window;"string"===typeof b&&(b=this.r(b));if(b){for(var d=this.da(b),a,c=0;f!=f.parent&&10>c;)c++,a=this.da(f.frameElement),d.left+=a.left,d.top+=a.top,f=f.parent;return d}},da:function(b){"string"===typeof b&&(b=this.r(b));var f=i.Ya(b),d=i.h;0<d.tc&&f.getBoxObjectFor&&this.t(b,"position");var a={left:0,top:0},
c;if(b==(d.g&&!d.Eb?f.body:f.documentElement)||!b)return a;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),a.left=Math.floor(b.left)+Math.max(f.documentElement.scrollLeft,f.body.scrollLeft),a.top=Math.floor(b.top)+Math.max(f.documentElement.scrollTop,f.body.scrollTop),a.left-=f.documentElement.clientLeft,a.top-=f.documentElement.clientTop,b=f.body,f=parseInt(this.t(b,"borderLeftWidth"),10),b=parseInt(this.t(b,"borderTopWidth"),10),d.g&&!d.Eb&&(a.left-=isNaN(f)?2:f,a.top-=isNaN(b)?2:b);else{c=
b;do{a.left+=c.offsetLeft;a.top+=c.offsetTop;if(0<d.Fb&&"fixed"==this.t(c,"position")){a.left+=f.body.scrollLeft;a.top+=f.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(0<d.opera||0<d.Fb&&"absolute"==this.t(b,"position"))a.top-=f.body.offsetTop;for(c=b.offsetParent;c&&c!=f.body;){a.left-=c.scrollLeft;if(!d.opera||"TR"!=c.tagName)a.top-=c.scrollTop;c=c.offsetParent}}return a},Bb:function(b,f){var b=this.r(b),d=b.offsetWidth;if(f||v)var a=this.t(b,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),c=this.t(b,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},Ab:function(b,f){var b=this.r(b),d=b.offsetHeight;if(f||v)var a=this.t(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.t(b,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},ad:function(b){var b=this.r(b),f=this.ab(b),d=0;
if(this.ra(window)&&!i.Fa(window)){for(;f.parent!=window.top&&10>d;)d++,f=f.parent;10>d&&(b=f.frameElement||b)}return b},zb:function(b){var f=this.r(b),b=this.ab(f),d=100,a;try{for(;f&&f.tagName;){a=100;if(this.h.g){if(5<this.h.g)try{a=f.Wc.alpha.opacity||100}catch(c){}d=d>a?a:d}else{try{a=100*(b.getComputedStyle(f,r).opacity||1)}catch(e){}d*=a/100}f=f.parentNode}}catch(g){}return d||100},Yc:function(b){for(var f=this.r(b),b=this.ab(f),f=this.zb(f),d=100,a=0;this.ra(b);){a++;if(i.Fa(b,b.parent))break;
else d=100,b.frameElement&&(d=this.zb(b.frameElement)),f*=d/100;b=b.parent}return f}}})});
G&&G("union/common/logic1419842093",[],function(){return{Vc:function(g){(g=g||"")&&(g=g.replace(/%u[\d|\w]{4}/g,function(g){return encodeURIComponent(unescape(g))}));return g},S:function(g,i){return g.replace(/{(.*?)}/g,function(e,g){return i[g]||""})},wc:function(g){return(new Function("return "+g))()},Cb:function(g,i){if(g&&i){var e=g.match(RegExp("(^|&|\\?|#)"+i+"=([^&]*)(&|$)",""));if(e)return e[2]}return r},hd:function(g,i){var g=g||"",i=i||"?",e=arguments.callee;e.hasOwnProperty[i]||(e[i]={});e=e[i];
if(e.hasOwnProperty(g))return e[g];var j={},b=g.indexOf(i),f=g.substring(b+1).split("&");if(-1!==b)for(var b=0,d=f.length;b<d;b++){var a=f[b].split("="),c=decodeURIComponent(a[0]),a=decodeURIComponent(a[1]);j.hasOwnProperty(c)?(j[c].constructor!==Array&&(j[c]=[j[c]]),j[c].push(a)):j[c]=a}return e[g]=j}}});
G&&G("union/preview1419842093",["union/common/bom1419842093","union/common/logic1419842093","union/common/cookie1419842093"],function(g,i,e){function j(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return i.wc(b)}function b(b,d){var a;a=d?d.substring(d.indexOf("?")):g.Fa(window)?window.location.search.slice(1):window.top.location.search.slice(1);var c=document.referrer,h=0<=b.indexOf("inlay")||"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",o="",p;try{p=document.cookie}catch(D){}-1!==
a.indexOf(h)&&(o=i.Cb(a,h));!o&&p&&-1!==p.indexOf(h)&&(o=e.X(h));!o&&-1!==c.indexOf(h)&&(o=i.Cb(c,h));return o}return{Za:function(f,d){var a=window.location.href,c=parseInt(f.rsi0,10),h=parseInt(f.rsi1,10),o=parseInt(f.at,10),p=v,e=b(d,a);if(e)if(e=j(e),o===k&&(o=1),1!==parseInt(e.type,10)&&2===(o&2))p=parseInt(e.imgWidth,10)===parseInt(c,10)&&parseInt(e.imgHeight,10)===parseInt(h,10);else if(1===parseInt(e.type,10)&&(1===(o&1)||64===(o&64)||32===(o&32)))p=l;return p?(c=0<=d.indexOf("inlay")||"ui"===
d?"bd_cpro_prev":"bd_cpro_fprev",a=b(d,a),h=f.tn,o=j(a),p=r,0<=d.indexOf("inlay")?p={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(o.type,10)?h+".html":2===parseInt(o.type,10)?"image.html":4===parseInt(o.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+c+"=#"+a+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===d&&(o=parseInt(o.type,10),o="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===o?"float_image.html":4===o?"float_flash.html":"blank_tips.html")+
"?",a="tn="+h+("&"+c+"="+a).replace(/\./g,"%252e")+"&ut="+ +new Date,p={serviceUrl:o,paramString:a}),p):r}}});
G&&G("union/business/businessLogic1419842093",["union/preview1419842093","union/common/dom1419842093"],function(g,i){var e={inlay:8,"float":2,patch:2,linkunit:20,popup:1},j={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},b={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{ta:function(b){var d=b._html||
{},a="",c="http://cb.baidu.com/ecom?",e=b.id.split("_")[0],i=parseInt(d.conW||0,10)||parseInt(b._w,10)||parseInt(b.sw,10)||parseInt(d.rsi0,10),j=parseInt(d.conH||0,10)||parseInt(b._h,10)||parseInt(b.sh,10)||parseInt(d.rsi1,10),D=b.displayType,B=d.tn||"",s=B.toLowerCase(),m=d.ch||0,b=b.qn||"",y=d.n||"",u=d.dai||0;d.dtm="BAIDU_DUP2_SETJSONADSLOT";d.dc="2";d.di=e;var a=[],n;for(n in d)n&&d.hasOwnProperty(n)&&a.push(""+n+"="+encodeURIComponent(d[n].toString()));a=a.join("&");if((n=g.Za(d,D))&&n.serviceUrl!==
k&&n.paramString!==k)c=n.serviceUrl,a=n.paramString;return{slotId:e,slotWidth:i,slotHeight:j,displayType:D,styleType:s,iframeId:"cproIframe_"+e+"_"+d.dai,unionAccount:y,adIndex:u,channel:m,pvId:b,stuffType:"unknown",serviceUrl:c,paramString:a,delayIn:d.delayIn,delayOut:d.delayOut,sessionSync:d.sessionSync!==v&&"false"!==d.sessionSync,closeFor:d.closeFor,xuantingType:d.xuanting,tn:B}},ib:function(b){var d={};d.$b=(b.$b||"pc").toLowerCase();d.C=(b.C||"inlay-fixed").toLowerCase();d.s=(b.s||"template_inlay_all_normal").toLowerCase();
d.N=(b.N||"text").toLowerCase();d.K=b.K;if(-1<d.s.indexOf("tlink")||-1<d.s.indexOf("linkunit"))d.C="linkunit-fixed";0<=d.s.indexOf("float_xuanfuwin")&&(d.C="popup-float");b=d.C.split("-");d.Sa=b[0]||"inlay";d.Uc=b[1]||"fixed";return d},na:function(b){var b=this.ib(b),d=b.Sa;return this.gc(b)<e[d]},gc:function(b){var b=this.ib(b),d=0,b=j[b.Sa],a;for(a in b)a&&b[a]&&b.hasOwnProperty(a)&&(i.m(a)?d++:b[a]=k);return d},va:function(b){b=this.ib(b);j[b.Sa][b.K]=1;return l},Da:function(b,d){var a=document.getElementById("cpro_"+
b);a||(a=document.getElementById(d));return a},ic:function(e){return b[e]},Vb:function(b){var d={"test.com":l,"people.com.cn":l,"chinanews.com":l,"cri.cn":l,"chinadaily.com":l,"cnki.com.cn":l,"cnki.net":l,"ku6.com":l,"tgbus.com":l,"5068.com":l,"yzz.cn":l,"aipai.com":l,"stockstar.com":l},b=b||window,a="",c=b.document.domain.split("."),e=c.length;e&&2<e?a="cn"===c[e-1]&&"com"===c[e-2]?c[e-3]+"."+c[e-2]+"."+c[e-1]:c[e-2]+"."+c[e-1]:e&&(a=b.document.domain);return a&&d[a]?v:l},Ja:function(b){var d=b.slotId;
E(["viewWatch"],function(a){a.register({id:d,wrapperId:b.iframeId,logType:"block",extra:"ch="+b.channel+"&jk="+b.pvId+"&n="+b.unionAccount})},l)}}});G&&G("union/floatad","union/common/oo1419842093,union/common/cookie1419842093,union/common/dom1419842093,union/common/bom1419842093,union/common/logic1419842093,union/business/businessLogic1419842093,union/preview1419842093".split(","),function(g,i,e,j,b,f,d){function a(c,h,a){if(!c||!c._html)return r;var b=f.ic(h),e=c._html,i="",g="http://cb.baidu.com/ecom?",j=c.id.split("_")[0],n=parseInt(e.conW||0,10)||parseInt(e.rsi0,10)||parseInt(c._w,10)||parseInt(c.sw,10),c=parseInt(e.conH||0,10)||parseInt(e.rsi1,10)||parseInt(c._h,10)||parseInt(c.sh,10),i=e.tn||"",t=i.toLowerCase(),
q=e.n||"",z=parseInt(e.ch||0,10),F=parseInt(e.dai||0,10);e.stid=0;var w=0<=i.indexOf("float")&&120===n&&270===c,C=v,A=parseInt(e.lunum,10);f.Vb(window)&&w&&(0<A&&(e.lunum=6,C=l),e.stid=2);e.dtm="BAIDU_DUP2_SETJSONADSLOT";e.dc="2";e.di=j;e.distp=h;0<=i.indexOf("float")&&(e.tn="template_float_all_normal");var i=[],x;for(x in e)x&&e.hasOwnProperty(x)&&i.push(""+x+"="+encodeURIComponent(e[x].toString()));i=i.join("&");if((x=d.Za(e,b))&&x.serviceUrl!==k&&x.paramString!==k)g=x.serviceUrl,i=x.paramString;
return{d:j,Jb:n,Ib:c,C:b,Wa:parseInt(e.rsi6,10),Va:parseInt(e.rsi7,10),Ra:parseInt(e.ccw,10),Qa:parseInt(e.ct,10),pa:parseInt(e.pt,10),ca:a,z:parseInt(e.fa,10),fc:parseInt(e.flw,10),nd:e.tn,Ha:e.qn,s:t,L:g,H:i,b:"cproIframe"+(h||parseInt(100+100*Math.random(),10)),fb:C,ia:q,aa:z,Ca:F,N:"unknown"}}function c(c){var h=c.slotId;E(["viewWatch"],function(a){a.register({id:h,wrapperId:c.b,logType:"block",extra:"ch="+c.aa+"&jk="+c.Ha+"&n="+c.ia})},l)}var h;g(function(c){h=c.Oa({ec:{1:{sb:1,rb:150},2:{sb:0,
rb:40},3:{sb:0,rb:0}},constructor:function(h){this.b=h.b;this.L=h.L;this.H=h.H;this.K=this.b+"holder";this.z=h.z;this.ca=h.ca;this.pa=h.pa;this.yb=h.fc;this.Q=h.Jb;this.P=h.Ib;this.ka=h.Jb;this.V=h.Ib;this.fb=h.fb;this.Ha=h.Ha;this.Wa=h.Wa;this.Va=h.Va;this.Ra=h.Ra;this.fb?(this.P+=80,this.V+=80):this.P+=20;this.vb=1===this.z?0:5;this.Q+=10;this.P+=10;1===this.z&&(this.ka+=10,this.V+=10);this.Lb=this.ec;this.Qa=h.Qa;this.d=h.d;this.B=j.B();e.bind(window,"resize",c.i(this.M,this));e.bind(window,"scroll",
c.i(this.M,this))},kb:function(){var h=document.createElement("div");h.style.cssText=["maring:0;padding:0;display:block;visibility:visible;border:none;background:none;float:none;overflow:hidden;position:absolute;","z-index:"+(1===this.z?2147483646:2147483647)+";","width:"+this.Q+"px;","height:"+(this.P+this.vb)+"px"].join("");h.id=this.K;var a="",e=document.createElement("div");e.id=this.b+"CloseBtnWrap";var f=document.createElement("div");f.id=this.b+"CloseBtn";1===this.z?(e.style.cssText=["position:absolute;top:275px;left:0;cursor:pointer;",
"width:"+this.Q+"px;","height:28px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;"].join(""),f.style.cssText=["position:absolute;","width:"+this.Q+"px;","height:20px;top:280px;left:0;cursor:pointer;background-color:#999999;color:#fff;font-size:12px;font-family: \u5fae\u8f6f\u96c5\u9ed1;text-align:center;line-height:20px;"].join(""),f.innerHTML="\u5173\u95ed"):(e.style.cssText=["position:absolute;top:0px;","left:"+(this.Q-61)+"px;","cursor:pointer;width:61px;height:20px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;margin:0;paddong:0;"].join(""),
f.style.cssText=["position:absolute;width:61px;height:20px;top:0;","left:"+(this.Q-61)+"px;","margin:0;padding:0;margin-bottom:5px;cursor:pointer;overflow:hidden;"].join(""),f.innerHTML='<div style="width:40px;height:20px;background-color:#999999;color:#fff;float:left;margin-right:1px;font-size:12px;font-family:\u5fae\u8f6f\u96c5\u9ed1;text-align: center;line-height:20px;">\u5173\u95ed</div><a style="maring:0;padding:0;display:inline-block;border:none;overflow:hidden;height:20px;line-height:20px;cursor:pointer;width:20px;background:url(\'http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png\') no-repeat 0 0;margin-bottom:3px;float:left" ></a>',
a="position:absolute;left:0;top:25px;");h.appendChild(e);h.appendChild(f);f=document.createElement("div");a=["width:"+this.ka+"px;","height:"+this.V+"px;","overflow:hidden;"+a];1!==this.z&&(a.push("padding:4px;"),a.push("border:#acacac 1px solid;"));f.style.cssText=a.join("");this.H+="&adclass=1&conW="+this.ka+"&conH="+this.V;f.innerHTML=b.S('<div style="display:none">-</div><iframe id="{iframeId}" src="{cproServiceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe></div>',
{iframeId:this.b,cproServiceUrl:this.L,paramString:this.H,iframeWidth:this.ka,iframeHeight:this.V});h.appendChild(f);this.ga(h);for(var a=document.body.children,f=a.length,d=10>a.length?a.length:10,i=document.body.lastChild,g=0;g<d;g++){var j=a[f-g-1].getAttribute("data-baidu-dan-id");if(j||""===j){i=a[f-g-1];break}}i.parentNode.insertBefore(h,i);e.onclick=c.i(this.Sb,this);e.onmouseover=c.i(this.Ub,this);e.onmouseout=c.i(this.Tb,this)},kc:function(){var c=2;return c=1===this.yb?this.B?1===this.pa?
4:3:1===this.pa?2:1:1===this.pa?6:5},jc:function(){var c=this.Va;return c=0>c||9999<c?0:Math.floor(c)},lc:function(){var c=this.Wa;return c=0>c||9999<c?this.Lb[this.z].rb:Math.floor(c)},hc:function(){var c=this.Ra;4095<c&&(c=4095);return c=Math.floor(c)},M:function(){this.wa&&clearTimeout(this.wa);this.wa=setTimeout(c.i(this.Fc,this),50)},Fc:function(){var c=document.getElementById(this.K);c&&this.ga(c)},ga:function(c){c.style.position=this.B?(1===this.z||2===this.z)&&2===this.yb?"absolute":"fixed":
"absolute";var h=j.F(window),a=j.$a(window),b=j.D(window),f=j.o(window),d=this.Q,o=this.P+this.vb,i=this.Lb[this.z].sb,g=e.t(document.body,"position").toString(),q=e.t(document.body,"width").toString().replace("px",""),z=this.kc(),F="right",w,C,A=this.jc(),x=this.lc();w=this.hc();var H=e.oc(document.body).left;w=Math.floor((b-w)/2)-d-10;w=0<=w&&0==z%2?w:7;switch(z){case 1:case 2:"relative"===g&&"auto"!=q&&b>q?(d=b-w-d-H,a=a+w-H):(d=a+b-w-d,a+=w);F="left";C=Math.max(1===i?f>=o+x?h+x:h+f-o:f>=o+x?h+
f-x-o:h,A);break;case 3:case 4:a=d=w;1===i?C=Math.max(f>=o+x?x:f-o,A-h):(C=Math.min(h+f-A-o,x),C=Math.min(C,f-o));break;case 5:case 6:"relative"===g&&"auto"!=q&&b>q?(d=b-(b-q)/2-w-d,a=a+w-(b-q)/2):(d=a+b-w-d,a+=w);F="left";C=Math.max(1===i?x:f>=o+x?f-x-o:0,A);break;default:a=d=10}if(1===z%4||2===z%4)i=1;h=i?"top":"bottom";1===(this.ca&1)?(c=c.style,c.left=a+"px",c[h]=C+"px",c.visibility="visible"):2===(this.ca&2)&&(c=c.style,c[F]=d+"px",c[h]=C+"px",c.visibility="visible")},Sb:function(){var c=document.getElementById(this.K);
if(2===this.Qa){var h="bd_close_"+this.d,a=i.X(h,window),a=a?a|this.ca:this.ca;i.ha(h,a,{path:"/"})}c.parentNode&&c.parentNode.removeChild?c.parentNode.removeChild(c):document.body.removeChild(c);c={jk:this.Ha||"",dt:(new Date).getTime(),rnd:Math.floor(2147483648*Math.random())};try{j.Ec(b.S("http://eclick.baidu.com/fcb.jpg?jk={jk}&dt={dt}&rnd={rnd}",c),window)}catch(f){}},Ub:function(){var c=document.getElementById(this.b+"CloseBtn");c&&(1===this.z?c.style.backgroundColor="#0066cc":(c.getElementsByTagName("div")[0].style.backgroundColor=
"#0066cc",c.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuanfu_mouseover_close.png)"))},Tb:function(){var c=document.getElementById(this.b+"CloseBtn");c&&(1===this.z?c.style.backgroundColor="#999999":(c.getElementsByTagName("div")[0].style.backgroundColor="#999999",c.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png)"))}})});return{render:function(b){var e;
if(j.ra())e=v;else if(e=parseInt(b._html.ww||0,10),4095<e&&(e=4095),e>=screen.width)e=v;else{var d=e=v;e=/iphone|ipod|android|blackberry|opera mini|opera mobi|skyfire|maemo|windows phone|palm|iemobile|symbian|symbianos|fennec/i.test(navigator.userAgent.toLowerCase());d=/ipad|android 3|sch-i800|playbook|tablet|kindle|gt-p1000|sgh-t849|shw-m180s|a510|a511|a100|dell streak|silk|SAMSUNG.*Tablet|Galaxy.*Tab|SC-01C|GT-P1000|GT-P1003|GT-P1010|GT-P3105|GT-P6210|GT-P6800|GT-P6810|GT-P7100|GT-P7300|GT-P7310|GT-P7500|GT-P7510|SCH-I800|SCH-I815|SCH-I905|SGH-I957|SGH-I987|SGH-T849|SGH-T859|SGH-T869|SPH-P100|GT-P3100|GT-P3108|GT-P3110|GT-P5100|GT-P5110|GT-P6200|GT-P7320|GT-P7511|GT-N8000|GT-P8510|SGH-I497|SPH-P500|SGH-T779|SCH-I705|SCH-I915|GT-N8013|GT-P3113|GT-P5113|GT-P8110|GT-N8010|GT-N8005|GT-N8020|GT-P1013|GT-P6201|GT-P7501|GT-N5100|GT-N5110|SHV-E140K|SHV-E140L|SHV-E140S|SHV-E150S|SHV-E230K|SHV-E230L|SHV-E230S|SHW-M180K|SHW-M180L|SHW-M180S|SHW-M180W|SHW-M300W|SHW-M305W|SHW-M380K|SHW-M380S|SHW-M380W|SHW-M430W|SHW-M480K|SHW-M480S|SHW-M480W|SHW-M485W|SHW-M486W|SHW-M500W|GT-I9228|SCH-P739|SCH-I925|GT-I9200|GT-I9205|GT-P5200|GT-P5210|SM-T311|SM-T310|SM-T210|SM-T211|SM-P900|IdeaTab|S2110|S6000|K3011|A3000|A1000|A2107|A2109|A1107/i.test(navigator.userAgent.toLowerCase());
e=1024>screen.width&&e&&!d?v:l}if(e){if(b&&b._html){var g=b._html;e=parseInt(g.fa,10);var d=parseInt(g.ls,10),s=b.id.split("_")[0],m=0;2===parseInt(g.ct,10)&&(m=parseInt(i.X("bd_close_"+s),10));g=[];1===e||2===e?(2===(d&2)&&2!==(m&2)&&g.push(a(b,"2002",2)),1===(d&1)&&1!==(m&1)&&g.push(a(b,"2001",1))):(d=3!==d?d:2,m!=d&&g.push(a(b,1===d?"2003":"2004",d)));b=g}else b=k;e=b.length;for(d=0;d<e;d++)if(m=b[d])g={C:m.C,s:m.s,N:m.N,K:m.b},f.na(g)&&((new h(m)).kb(),f.va(g),c(m))}}}});
})();
