/*! ver:1419842093 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var k=void 0,l=!0,r=null,v=!1,E=window.BAIDU_DUP_require,G=window.BAIDU_DUP_define;
G&&G("union/common/cookie1419842093",[],function(){return{X:function(g,i){var e,j=RegExp("(^| )"+g+"=([^;]*)(;|$)").exec((i||window).document.cookie);j&&(e=j[2]);return e},ha:function(g,i,e){var e=e||{},j=e.ba;"number"==typeof e.ba&&(j=new Date,j.setTime(j.getTime()+e.ba));document.cookie=""+g+"="+i+(e.path?"; path="+e.path:"")+(j?"; expires="+j.toGMTString():"")+(e.domain?"; domain="+e.domain:"")+(e.ld?"; secure":"")},remove:function(g){var i=new Date;i.setTime(i.getTime()-86400);this.ha(g,"",{path:"/",ba:i})}}});
G&&G("union/common/bom1419842093",[],function(){var g={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(g.g=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Xc=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(g.kd=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(g.Tc=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.ed)&&
(g.fd=+RegExp.$1)}catch(i){}g.Fb=/webkit/i.test(navigator.userAgent);g.tc=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);g.Eb="CSS1Compat"==document.compatMode;return{h:g,B:function(){var e=l;if(this.h.g&&(7>this.h.g||"BackCompat"===document.compatMode))e=v;return e},$c:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.scrollWidth:e.document.documentElement.scrollWidth}catch(g){return 0}},Zc:function(e){try{return e=e||window,"BackCompat"===
e.document.compatMode?e.document.body.scrollHeight:e.document.documentElement.scrollHeight}catch(g){return 0}},D:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientWidth:e.document.documentElement.clientWidth}catch(g){return 0}},o:function(e){try{return e=e||window,"BackCompat"===e.document.compatMode?e.document.body.clientHeight:e.document.documentElement.clientHeight}catch(g){return 0}},F:function(e){e=(e||window).document;return window.pageYOffset||e.documentElement.scrollTop||
e.body.scrollTop},$a:function(e){e=(e||window).document;return window.pageXOffset||e.documentElement.scrollLeft||e.body.scrollLeft},Gb:function(e){var g=v;try{e&&"object"===typeof e&&e.document&&"setInterval"in e&&(g=l)}catch(b){g=v}return g},ra:function(e){e=e||window;return e!=window.top&&e!=e.parent||!this.Gb(e)},Fa:function(e,g){for(var g=2===arguments.length?g:e.parent,b=0;10>b++&&this.ra(e,g);){var f;try{f=!!e.parent.location.toString()}catch(d){f=v}if(!f)return l;e=e.parent}return 10<=b?l:
v},Ec:function(e,g){var b=new Image,f="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),g=g||window;g[f]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=r;b=g[f]=r};b.src=e},Ya:function(e){if(!e)return document;"string"===typeof e&&(e=document.getElementById(e));return 9===e.nodeType?e:e.ownerDocument||e.document},ab:function(e){"string"===typeof e&&(e=document.getElementById(e));e=this.Ya(e);return e.parentWindow||e.defaultView||r},bd:function(e){e=e||window;return this.ra(e)&&
!this.Fa(e,e.top)&&this.Gb(e.top)?e.top:e}}});
G&&G("union/common/oo1419842093",[],function(){function g(b){var f=g.create(g);return b.call(f,f,f.tb)}function i(b,f){if(b.constructor===Array)for(var d=0,a=b.length;d<a;d++){if(f.call(b,b[d],d,b)===v)return v}else{var d=!{toString:1}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(a in b)if(b.hasOwnProperty(a)&&f.call(b,b[a],a,b)===v)return v;if(d){d=0;for(a=c.length;d<a;d++){var e=c[d];if(b.hasOwnProperty(e)&&
f.call(b,e,d,b)===v)return v}}}return l}function e(b,f,d){i(f,function(a,c){if(!b.hasOwnProperty(c)||d)b[c]=a})}function j(b){function f(){}if(Object.create)return Object.create(b);f.prototype=b;return new f}g.tb={};g.create=j;g.bc=i;g.Oa=function(b){var f,d=b.hasOwnProperty("constructor")?b.constructor:function(){};d.prototype=b;d.prototype.constructor=d;f=f||{};f.lb&&e(d,f.lb);return d};g.extend=function(b,f,d){var a;a=f.hasOwnProperty("constructor")?f.constructor:function(){b.constructor.apply(this,
arguments)};a.prototype=j(b.prototype);e(a.prototype,f,l);a.prototype.constructor=a;a.prototype.Qc=b.prototype;e(a,b);d=d||{};d.lb&&e(a,d.lb,l);return a};g.gd=function(b){var f=this.tb;i(b.split("."),function(b){f.hasOwnProperty(b)||(f[b]={});f=f[b]});return f};g.i=function(b,f){var d;return function(){d=d||[];for(var a=0,c=arguments.length;a<c;a++)d.push(arguments[a]);return b.apply(f||{},d)}};return g});
G&&G("union/common/dom1419842093",["union/common/oo1419842093","union/common/bom1419842093"],function(g,i){return g(function(e){var g=i.h;return{m:function(b,f){return"string"===typeof b||b instanceof String?(f||window).document.getElementById(b):b},Db:function(b,f){var d=l;if("string"===typeof f)return b.id===f;if(f.constructor===Object)return e.bc(f,function(a,c){var f=(b.getAttribute?b.getAttribute(c):b[c])||b[c];if("tagName"===c){if(f.toUpperCase()!=a.toUpperCase())return d=v}else if(f!=a)return d=v}),d;if(f.constructor===
Array){var a=f.concat([]);a.reverse();for(var c=b;c&&a.length;c=c.parentNode)this.Db(c,a[0])&&a.shift();return!a.length?l:v}},Nb:function(b,f){if(b&&f(b)!==v){var d=b.childNodes;if(d)for(var a=0,c=d.length;a<c;a++)if(this.Nb(d[a],f)===v)return v}},Kb:function(b,f){var d=this;b.constructor===Object&&(b=this.r(b));if("string"===typeof f){for(var a=document.getElementById(f),c=a;c;){if(c===b)return a;c=c.parentNode}return r}if(f.constructor===Object){var e=r;d.Nb(b,function(a){if(d.Db(a,f))return e=
a,v});return e}},r:function(b){if(b){if(b.nodeName)return b;1<arguments.length&&(b=Array.prototype.slice.call(arguments,0));if("string"===typeof b)return document.getElementById(b);if(b.constructor===Object)return this.Kb(document.documentElement,b);if(b.constructor===Array){for(var f=b.concat([]),d=document.documentElement;f.length&&d;)d=this.Kb(d,f.shift());return d}}},Cc:function(b,f,d){var d=d||this.pd||window,a=d.document;this.xb=0;this.ea=this.ea||[];this.ea.push({Xa:b,wb:f||0,Ta:v});var c=
e.i(function(){var c=v;this.xb++;var b=v;try{d.frameElement&&(b=l)}catch(f){b=l}if(g.g&&9>g.g&&!b)try{a.documentElement.doScroll("left"),c=l}catch(e){}else if("complete"===a.readyState||this.ac)c=l;else if(3E5<this.xb){this.W&&(d.clearInterval(this.W),this.W=r);return}if(c)try{if(this.ea&&this.ea.length)for(var c=0,i=this.ea.length;c<i;c++){var s=this.ea[c];s&&s.Xa&&!s.Ta&&(s.wb?(s.Ta=l,d.setTimeout(s.Xa,s.wb)):(s.Ta=l,s.Xa()))}}catch(m){throw m;}finally{this.W&&(d.clearInterval(this.W),this.W=r)}},
this),b=e.i(function(){this.ac=l;c()},this);this.W||(this.W=d.setInterval(c,50),a.addEventListener?(a.addEventListener("DOMContentLoaded",b,v),d.addEventListener("load",b,v)):a.attachEvent&&d.attachEvent("onload",b,v))},B:function(){var b=l;if(g.g&&(7>g.g||"BackCompat"===document.compatMode))b=v;return b},bind:function(b,f,d){"string"===typeof b&&(b=this.r(b));f=f.replace(/^on/i,"").toLowerCase();b.addEventListener?b.addEventListener(f,d,v):b.attachEvent&&b.attachEvent("on"+f,d);return b},Ob:function(b,
f,d){b=this.r(b);if(!b)return r;f=f.replace(/^on/i,"").toLowerCase();b.removeEventListener?b.removeEventListener(f,d,v):b.detachEvent&&b.detachEvent("on"+f,d);return b},t:function(b,f){var d;"string"===typeof b&&(b=this.r(b));var a=i.Ya(b),c="",c=-1<f.indexOf("-")?f.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):f.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});a&&a.defaultView&&a.defaultView.getComputedStyle?((a=a.defaultView.getComputedStyle(b,r))&&
(d=a.getPropertyValue(f)),"boolean"!==typeof d&&!d&&(d=a.getPropertyValue(c))):b.currentStyle&&((a=b.currentStyle)&&(d=a[f]),"boolean"!==typeof d&&!d&&(d=a[c]));return d},oc:function(b,f){f=f||window;"string"===typeof b&&(b=this.r(b));if(b){for(var d=this.da(b),a,c=0;f!=f.parent&&10>c;)c++,a=this.da(f.frameElement),d.left+=a.left,d.top+=a.top,f=f.parent;return d}},da:function(b){"string"===typeof b&&(b=this.r(b));var f=i.Ya(b),d=i.h;0<d.tc&&f.getBoxObjectFor&&this.t(b,"position");var a={left:0,top:0},
c;if(b==(d.g&&!d.Eb?f.body:f.documentElement)||!b)return a;if(b.getBoundingClientRect)b=b.getBoundingClientRect(),a.left=Math.floor(b.left)+Math.max(f.documentElement.scrollLeft,f.body.scrollLeft),a.top=Math.floor(b.top)+Math.max(f.documentElement.scrollTop,f.body.scrollTop),a.left-=f.documentElement.clientLeft,a.top-=f.documentElement.clientTop,b=f.body,f=parseInt(this.t(b,"borderLeftWidth"),10),b=parseInt(this.t(b,"borderTopWidth"),10),d.g&&!d.Eb&&(a.left-=isNaN(f)?2:f,a.top-=isNaN(b)?2:b);else{c=
b;do{a.left+=c.offsetLeft;a.top+=c.offsetTop;if(0<d.Fb&&"fixed"==this.t(c,"position")){a.left+=f.body.scrollLeft;a.top+=f.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(0<d.opera||0<d.Fb&&"absolute"==this.t(b,"position"))a.top-=f.body.offsetTop;for(c=b.offsetParent;c&&c!=f.body;){a.left-=c.scrollLeft;if(!d.opera||"TR"!=c.tagName)a.top-=c.scrollTop;c=c.offsetParent}}return a},Bb:function(b,f){var b=this.r(b),d=b.offsetWidth;if(f||v)var a=this.t(b,"marginLeft").toString().toLowerCase().replace("px",
"").replace("auto","0"),c=this.t(b,"marginRight").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},Ab:function(b,f){var b=this.r(b),d=b.offsetHeight;if(f||v)var a=this.t(b,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),c=this.t(b,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),d=d+(parseInt(a||0,10)+parseInt(c||0,10));return d},ad:function(b){var b=this.r(b),f=this.ab(b),d=0;
if(this.ra(window)&&!i.Fa(window)){for(;f.parent!=window.top&&10>d;)d++,f=f.parent;10>d&&(b=f.frameElement||b)}return b},zb:function(b){var f=this.r(b),b=this.ab(f),d=100,a;try{for(;f&&f.tagName;){a=100;if(this.h.g){if(5<this.h.g)try{a=f.Wc.alpha.opacity||100}catch(c){}d=d>a?a:d}else{try{a=100*(b.getComputedStyle(f,r).opacity||1)}catch(e){}d*=a/100}f=f.parentNode}}catch(g){}return d||100},Yc:function(b){for(var f=this.r(b),b=this.ab(f),f=this.zb(f),d=100,a=0;this.ra(b);){a++;if(i.Fa(b,b.parent))break;
else d=100,b.frameElement&&(d=this.zb(b.frameElement)),f*=d/100;b=b.parent}return f}}})});
G&&G("union/common/logic1419842093",[],function(){return{Vc:function(g){(g=g||"")&&(g=g.replace(/%u[\d|\w]{4}/g,function(g){return encodeURIComponent(unescape(g))}));return g},S:function(g,i){return g.replace(/{(.*?)}/g,function(e,g){return i[g]||""})},wc:function(g){return(new Function("return "+g))()},Cb:function(g,i){if(g&&i){var e=g.match(RegExp("(^|&|\\?|#)"+i+"=([^&]*)(&|$)",""));if(e)return e[2]}return r},hd:function(g,i){var g=g||"",i=i||"?",e=arguments.callee;e.hasOwnProperty[i]||(e[i]={});e=e[i];
if(e.hasOwnProperty(g))return e[g];var j={},b=g.indexOf(i),f=g.substring(b+1).split("&");if(-1!==b)for(var b=0,d=f.length;b<d;b++){var a=f[b].split("="),c=decodeURIComponent(a[0]),a=decodeURIComponent(a[1]);j.hasOwnProperty(c)?(j[c].constructor!==Array&&(j[c]=[j[c]]),j[c].push(a)):j[c]=a}return e[g]=j}}});
G&&G("union/preview1419842093",["union/common/bom1419842093","union/common/logic1419842093","union/common/cookie1419842093"],function(g,i,e){function j(b){b=decodeURIComponent(b).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return i.wc(b)}function b(b,d){var a;a=d?d.substring(d.indexOf("?")):g.Fa(window)?window.location.search.slice(1):window.top.location.search.slice(1);var c=document.referrer,h=0<=b.indexOf("inlay")||"ui"===b?"bd_cpro_prev":"bd_cpro_fprev",o="",p;try{p=document.cookie}catch(D){}-1!==
a.indexOf(h)&&(o=i.Cb(a,h));!o&&p&&-1!==p.indexOf(h)&&(o=e.X(h));!o&&-1!==c.indexOf(h)&&(o=i.Cb(c,h));return o}return{Za:function(f,d){var a=window.location.href,c=parseInt(f.rsi0,10),h=parseInt(f.rsi1,10),o=parseInt(f.at,10),p=v,e=b(d,a);if(e)if(e=j(e),o===k&&(o=1),1!==parseInt(e.type,10)&&2===(o&2))p=parseInt(e.imgWidth,10)===parseInt(c,10)&&parseInt(e.imgHeight,10)===parseInt(h,10);else if(1===parseInt(e.type,10)&&(1===(o&1)||64===(o&64)||32===(o&32)))p=l;return p?(c=0<=d.indexOf("inlay")||"ui"===
d?"bd_cpro_prev":"bd_cpro_fprev",a=b(d,a),h=f.tn,o=j(a),p=r,0<=d.indexOf("inlay")?p={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(o.type,10)?h+".html":2===parseInt(o.type,10)?"image.html":4===parseInt(o.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+c+"=#"+a+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===d&&(o=parseInt(o.type,10),o="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===o?"float_image.html":4===o?"float_flash.html":"blank_tips.html")+
"?",a="tn="+h+("&"+c+"="+a).replace(/\./g,"%252e")+"&ut="+ +new Date,p={serviceUrl:o,paramString:a}),p):r}}});
G&&G("union/business/businessLogic1419842093",["union/preview1419842093","union/common/dom1419842093"],function(g,i){var e={inlay:8,"float":2,patch:2,linkunit:20,popup:1},j={inlay:{},"float":{},patch:{},linkunit:{},popup:{}},b={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{ta:function(b){var d=b._html||
{},a="",c="http://cb.baidu.com/ecom?",e=b.id.split("_")[0],i=parseInt(d.conW||0,10)||parseInt(b._w,10)||parseInt(b.sw,10)||parseInt(d.rsi0,10),j=parseInt(d.conH||0,10)||parseInt(b._h,10)||parseInt(b.sh,10)||parseInt(d.rsi1,10),D=b.displayType,B=d.tn||"",s=B.toLowerCase(),m=d.ch||0,b=b.qn||"",y=d.n||"",u=d.dai||0;d.dtm="BAIDU_DUP2_SETJSONADSLOT";d.dc="2";d.di=e;var a=[],n;for(n in d)n&&d.hasOwnProperty(n)&&a.push(""+n+"="+encodeURIComponent(d[n].toString()));a=a.join("&");if((n=g.Za(d,D))&&n.serviceUrl!==
k&&n.paramString!==k)c=n.serviceUrl,a=n.paramString;return{slotId:e,slotWidth:i,slotHeight:j,displayType:D,styleType:s,iframeId:"cproIframe_"+e+"_"+d.dai,unionAccount:y,adIndex:u,channel:m,pvId:b,stuffType:"unknown",serviceUrl:c,paramString:a,delayIn:d.delayIn,delayOut:d.delayOut,sessionSync:d.sessionSync!==v&&"false"!==d.sessionSync,closeFor:d.closeFor,xuantingType:d.xuanting,tn:B}},ib:function(b){var d={};d.$b=(b.$b||"pc").toLowerCase();d.C=(b.C||"inlay-fixed").toLowerCase();d.s=(b.s||"template_inlay_all_normal").toLowerCase();
d.N=(b.N||"text").toLowerCase();d.K=b.K;if(-1<d.s.indexOf("tlink")||-1<d.s.indexOf("linkunit"))d.C="linkunit-fixed";0<=d.s.indexOf("float_xuanfuwin")&&(d.C="popup-float");b=d.C.split("-");d.Sa=b[0]||"inlay";d.Uc=b[1]||"fixed";return d},na:function(b){var b=this.ib(b),d=b.Sa;return this.gc(b)<e[d]},gc:function(b){var b=this.ib(b),d=0,b=j[b.Sa],a;for(a in b)a&&b[a]&&b.hasOwnProperty(a)&&(i.m(a)?d++:b[a]=k);return d},va:function(b){b=this.ib(b);j[b.Sa][b.K]=1;return l},Da:function(b,d){var a=document.getElementById("cpro_"+
b);a||(a=document.getElementById(d));return a},ic:function(e){return b[e]},Vb:function(b){var d={"test.com":l,"people.com.cn":l,"chinanews.com":l,"cri.cn":l,"chinadaily.com":l,"cnki.com.cn":l,"cnki.net":l,"ku6.com":l,"tgbus.com":l,"5068.com":l,"yzz.cn":l,"aipai.com":l,"stockstar.com":l},b=b||window,a="",c=b.document.domain.split("."),e=c.length;e&&2<e?a="cn"===c[e-1]&&"com"===c[e-2]?c[e-3]+"."+c[e-2]+"."+c[e-1]:c[e-2]+"."+c[e-1]:e&&(a=b.document.domain);return a&&d[a]?v:l},Ja:function(b){var d=b.slotId;
E(["viewWatch"],function(a){a.register({id:d,wrapperId:b.iframeId,logType:"block",extra:"ch="+b.channel+"&jk="+b.pvId+"&n="+b.unionAccount})},l)}}});G&&G("union/xuanting","union/common/cookie1419842093,union/common/bom1419842093,union/common/dom1419842093,union/common/logic1419842093,union/common/oo1419842093,union/business/businessLogic1419842093".split(","),function(g,i,e,j,b,f){var d;b(function(a){d=a.Oa({constructor:function(c){var h=c.Aa.id;this.Aa=e.r(c.Aa);this.type=+c.type;this.src=c.src;this.width=c.width;this.height=c.height;this.s=c.s||"";this.mb=c.mb||"";this.aa=c.aa||"0";this.ia=c.ia||"";this.ua=c.ua||"";this.I=this.pb=5;this.H=c.H;this.L=c.L;this.d=c.d;this.J="bd_close_"+this.d;this.Kc=!!g.X(this.J);
this.b=this.mc(this.d);this.q=h;this.c="";this.fileName="c";this.Ca=c.Ca||0;this.backgroundColor=c.backgroundColor;this.ma=c.ma;2===this.type?this.c="top":3===this.type&&(this.c="bottom");this.c&&(this.za=l,this.v=+c.v||0,this.w=+c.w||0,this.u=!!c.u||v,this.j=+c.j||0,this.Pa=500);this.R=c.R||v},cd:function(c){return"string"===typeof c?document.getElementById(c):c},Hc:function(c,h){return(h||document).getElementsByTagName(c)[0]},Mb:function(c,h){return c.replace(/\{(.*?)\}/g,function(c,a){return h.hasOwnProperty(a)?
h[a]:c})},mc:function(c){return"cproIframe_"+c},h:i.h,Ia:function(){var c={path:""};if(this.j&&!this.u){var h=new Date;h.setTime(h.getTime()+this.j);c.ba=h}g.ha(this.J,1,c)},Dc:function(c){var h=new Date;h.setTime(h.getTime()-86400);g.ha(c,"",{path:"/",ba:h})},M:function(){this.clientWidth=i.D(window);this.clientHeight=i.o(window);this.c&&(this.p&&(this.p.style.width=this.clientWidth+"px"),this.T&&(this.T.style.width=this.clientWidth+"px"));this.wa&&clearTimeout(this.wa);this.wa=setTimeout(a.i(this.sa,
this),5)},sa:function(){var c=this.p;if(c)if(e.B()){if(c.style.zIndex=2147483646,1===this.type)if("fixed"==c.style.position)this.la(),this.Rb()&&(c.style.cssText=r,this.jb());else{var h=this.qb();h&&(this.oa(),c.style.position="fixed",c.style.top=h+"px",this.la())}}else this.ga(this.p)},Rb:function(c){var h;c?(h=document.getElementById(c),c=document.getElementById(""+c+"placeholder")):(h=this.p||document.getElementById(this.q),c=document.getElementById(""+this.q+"placeholder"));return h&&c&&(c=this.k(c).La,
this.k(h).La<=c)?l:v},la:function(c){var h;c?(h=document.getElementById(c),c=document.getElementById(""+c+"placeholder")):(h=this.p||document.getElementById(this.q),c=document.getElementById(""+this.q+"placeholder"));h&&c&&(c=this.k(c).left,h.style.left=c+"px")},k:function(c){var h=e.da(c),a=i.$a(window),b=i.F(window),f=e.Bb(c,v),c=e.Ab(c,v);return{top:h.top-b,bottom:h.top-b+c,left:h.left-a,right:h.left-a+f,La:h.top,Sc:h.top+c,Ga:h.left,jd:h.left+f}},ga:function(){this.clientWidth=i.D(window);this.clientHeight=
i.o(window);var c=i.F(window),h=e.t(document.body,"position").toString(),a=e.da(document.body),b=a.left,f=a.top;if(a=this.p)if(a.style.position="absolute",a.style.zIndex=2147483646,1===this.type)if(document.getElementById(""+this.q+"placeholder")){var d=document.getElementById(""+this.q+"placeholder"),g=this.k(d);a.style.top=""+(c+this.I)+"px";a.style.left=""+g.Ga+"px";"relative"==h&&(a.style.top=c+this.I-f+"px",a.style.left=g.Ga-b+"px");a.style.visibility="visible";c=this.k(a);g.La>=c.La&&(a.parentNode.removeChild(a),
d.parentNode.insertBefore(a,d),d.parentNode.removeChild(d),a.style.cssText=r)}else{if(d=this.Ic(this.q))this.I=d,this.oa(this.q),d=document.getElementById(""+this.q+"placeholder"),g=this.k(d),a.parentNode.removeChild(a),document.body.appendChild(a),a.style.zIndex=2147483646,a.style.top=c+this.I+"px",a.style.left=g.Ga+"px","relative"==h&&(a.style.top=c+this.I-f+"px",a.style.left=g.Ga-b+"px"),a.style.visibility="visible",a.style.position="absolute"}else 2===this.type?a.style.top=c+"px":3===this.type&&
(a.style.top=c+this.clientHeight-(this.height+10)+"px")},kb:function(){if(!this.R){var c=this.type,a=this.width,b=this.height,f={srcAttrName:c===k||1==c?"src":"_src",iframeWidth:a,iframeHeight:b,iframeId:this.b,paramString:this.H||"",serviceUrl:this.L};this.Bc();var d=v;if(c&&(1===c||2===c||3===c)){var i=d="auto",g;if(1===c)g="inline-block",d=a+"px",i=b+"px";else if(2===c||3===c)g="block",d="100%",i=+b+10+"px";f.widthValue=d;f.heightValue=i;f.displayValue=g;c=this.Aa;c.setAttribute("width",d);c.setAttribute("height",
i);c.style.cssText=this.Mb("width:{widthValue};height:{heightValue};display:{displayValue};",f);d=l}f=this.Mb('<iframe id="{iframeId}" {srcAttrName}="{serviceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" ></iframe>',f);this.Aa.innerHTML=f;this.Ea=e.r(this.b);d&&(this.p=this.Ea.parentNode);this.Zb();this.Jc()}},Zb:function(){var c=this.type,a=this.Ea,b=this.p;if(c){var f=
1;if(2===c)f=2;else if(3===c)f=1;else if(1!==c&&0!==c&&this.p){this.p.style.display="none";return}var d=2===c||3===c,g="";switch(c){case 2:case 3:var g="display:none;",j="";this.h.g&&7>this.h.g&&(j="_background-image:none;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+f+".png');");f=d?'<div id="'+this.b+'WrapToggle" style="z-index:2147483646;cursor:pointer;position:absolute;right:0;'+this.c+":0;width:40px;height:100%;background-color:"+
this.backgroundColor+';"><div style="width:20px;height:22px;position:absolute;top:50%;margin-top:-11px;left:50%;margin-left:-10px;background:no-repeat url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk'+f+".png);"+j+'"></div></div>':"";d=d?'<div id="'+this.b+'WrapBk" style="'+this.c+":0;left:0;position:absolute;width:100%;height:100%;background-color:"+this.backgroundColor+";-moz-opacity:"+this.ma/100+";filter:alpha(opacity="+this.ma+");opacity:"+this.ma/100+';"></div>':"";j="";e.B()?
1===c?j="position:fixed;top:0;":2===c?j="position:fixed;top:0;width:100%;":3===c&&(j="position:fixed;bottom:0;width:100%;"):1===c?j="position:absolute;top:0;":2===c?j="position:absolute;top:0;width:100%;":3===c&&(j="position:absolute;top:"+(i.F(window)+i.o(window)-this.width)+"px;width:100%;");b.insertAdjacentHTML("afterBegin",d+f);b.style.cssText=[g,"height:",this.height+10,"px;right:0;z-index:2147483646;text-align:center;font-size:0;_overflow-y:hidden;",j].join("");a.style.cssText="position:relative;margin:5px 0;";
this.nb=e.r(""+this.b+"WrapToggle");this.Ka=this.Hc("DIV",this.nb);this.T=e.r(this.b+"WrapBk");this.M()}}},Ja:function(){var c=this.d,a=this.q,b=this;E(["viewWatch"],function(f){f.register({id:c,wrapperId:a,logType:"block",extra:"ch="+b.aa+"&jk="+b.ua+"&n="+b.ia})},l)},Jc:function(){var c=this,h=c.p,b=c.type,f=c.Ea,c=this;this.c?this.Kc?h.parentNode.removeChild(h):(setTimeout(function(){h.style.display="block";if(2===b||3===b){var a=f.getAttribute("_src");a&&(f.setAttribute("src",a),f.removeAttribute("_src"),
c.Ja())}},this.v),this.w&&setTimeout(function(){h.style.display="none"},this.v+this.w)):this.Ja();this.nb&&(2===this.type||3===this.type)&&e.bind(this.nb,"click",a.i(this.ob,this));e.bind(window,"scroll",a.i(this.sa,this));e.bind(window,"resize",a.i(this.sa,this))},Bc:function(){for(var c=1;2>=c;c++)(function(c){var a="bkimg_"+ +new Date+Math.floor(1E5*Math.random()),b=window[a]=new Image;b.onload=b.onerror=function(){b.onload=b.onerror=r;b=window[a]=r};b.src="http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+
c+".png"})(c)},ob:function(){this.za?this.bb():this.show()},xa:function(c){if(!this.$){this.$=l;var a=this.p,b=this.T,f=this.Ea,d=this.c,e=a.offsetHeight,i=Math.round(this.Pa/e),g=0,j=this;c&&(a.style.width="100%");var u=+new Date,n=setInterval(function(){var a=g=Math.round((+new Date-u)/i),h=a;c&&(h=e-a);b.style[d]=-h+"px";f.style[d]=-h+"px";a>=e&&(j.$=v,(j.za=c)&&"top"===d||!c&&"bottom"===d?j.h.g&&7>j.h.g?j.Ka.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png');":
j.Ka.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png)":j.h.g&&7>j.h.g?j.Ka.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png');":j.Ka.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png)",h=e,c&&(h=0),b.style[d]=-h+"px",f.style[d]=-h+"px",clearInterval(n))},i)}},show:function(){(this.u||this.j)&&this.Dc(this.J);this.xa(l)},
bb:function(){(this.u||this.j)&&this.Ia();this.xa(v)},oa:function(c){var a;c?(a=document.getElementById(c),c+="placeholder"):(a=this.p||document.getElementById(this.q),c=this.q+"placeholder");var b=document.createElement("div");b.id=c;b.align&&(b.align=a.getAttribute("align"));b.style.width=""+parseInt(a.getAttribute("width"),10)+"px";b.style.height=""+parseInt(a.getAttribute("height"),10)+"px";b.style.margin="0";b.style.padding="0";b.style.background="none";b.style.border="none";1===this.type&&(b.style.display=
"inline-block");a.parentNode.insertBefore(b,a);return l},jb:function(c){c=document.getElementById(c?c+"placeholder":this.q+"placeholder");c.parentNode.removeChild(c);return l},qb:function(c){var a=this.pb;return this.k(c?document.getElementById(c):this.p||document.getElementById(this.q)).top<a?a:v},Ic:function(c){var a=this.pb;return this.k(c?document.getElementById(c):this.p||document.getElementById(this.q)).top<a?a:v}})});return{render:function(a,c){switch(parseInt(a._html.xuanting,10)){case 1:a.displayType=
"inlay-float";break;case 2:a.displayType="float-top";break;case 3:a.displayType="float-bottom";break;default:a.displayType="inlay-float"}var b=f.ta(a);b.backgroundColor=a._html.rss1||"#666";b.backgroundOpacity=parseInt(a._html.opacity||60,10);var e=f.Da(b.slotId,c),i={C:b.displayType,s:b.styleType,N:b.stuffType};if(!f.na(i))return v;(new d({Aa:e,d:b.slotId,type:b.xuantingType,src:"",width:b.slotWidth,height:b.slotHeight,backgroundColor:b.backgroundColor,ma:b.backgroundOpacity,s:b.styleType,mb:b.tn,
aa:b.channel,ia:b.unionAccount,Ca:b.adIndex,ua:b.pvId,v:b.delayIn,w:b.delayOut,u:b.sessionSync,j:b.closeFor,H:b.paramString,L:b.serviceUrl})).kb();f.va(i)}}});
})();
