/*ebPreServing.js - v_2_15_0_0 - 2014-10-14*/
EBP="undefined"!=typeof EBP?EBP:{};EBP.Light=EBP.Light||{};EBP.Light.Infra=function(){};EBP.Light.Infra.isDefined=function(a){return"undefined"!=typeof a};EBP.Light.Infra.getTimestamp=function(){var a=new Date;return parseInt(a.getHours()+1)+":"+a.getMinutes()+":"+a.getSeconds()+"."+a.getMilliseconds()+" "+a.getDate()+"."+parseInt(a.getMonth()+1)+"."+a.getFullYear()};
EBP.Light.Infra.getUrlParameter=function(a){var b="",c=EBP.Light.Infra.getWindowLocation().toString(),d=RegExp("[&,?]"+a+"=(.*)$","i");if((a=c.match(RegExp("[&,?]"+a+"=(.*)[&]","i"))||c.match(d))&&0<a.length)-1<a[1].indexOf("&")&&(a[1]=a[1].substr(0,a[1].indexOf("&"))),b=a[1];return b};EBP.Light.Infra.combinePaths=function(a,b){a=a||"";b=b||"";a&&"/"!=a[a.length-1]&&(a+="/");var c=a;b&&(c+=b);return c};
EBP.Light.Infra.isPageLoaded=function(){var a=!0;"complete"!=document.readyState&&"loaded"!=document.readyState&&"interactive"!=document.readyState&&(a=!1);return a};EBP.Light.Infra.addChildToPage=function(a,b,c,d){if("undefined"==typeof b||!b)b=document.body||document.getElementsByTagName("head")[0];this.isDefined(c)&&null!=c&&this.addEventListener(a,c,d);b.appendChild(a)};
EBP.Light.Infra.addEventListener=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):(b="on"+b,a.attachEvent?a.attachEvent(b,c):b in a&&(a[b]=c))};EBP.Light.Infra.createScriptElement=function(a,b,c,d){try{var e=a.createElement(b);e.type=c;e.src=d;e.async=!1;return e}catch(h){}};
EBP.Light.Infra.addScriptElement=function(a,b){var c;if(b){if(c=b,0==c.childNodes.length){var d=document.createElement("div");d.style.display="none";b.appendChild(d)}}else c=document.head||document.documentElement;c.insertBefore(a,c.firstChild)};EBP.Light.Infra.getWindowLocation=function(){return window.location};EBP.Light.Infra.getRandomNumber=function(){try{var a=Math.random().toString();return a=a.substr(a.indexOf(".")+1)}catch(b){}};
EBP.Light.Infra.getAddInEyeDomain=function(a){var b="",c="",d=0,a=(a?a:window).document,a=a.referrer?a.referrer:a.location.href;try{a=a.toLowerCase(),7<=a.length&&"http://"==a.substr(0,7)?(c=a.substr(7),a.substr(0,7)):8<=a.length&&"https://"==a.substr(0,8)?(c=a.substr(8),a.substr(0,8)):c=a,d=c.indexOf("/"),0<d&&(c=c.substr(0,d)),b=c}catch(e){b=""}return b};
EBP.Light.Infra.createFriendlyIframe=function(a,b,c,d){a=(a?a:document).createElement("iframe");b&&a.setAttribute("id",b);a.style.display=c?"":"none";a.style.width=c?c+"px":"0px";a.style.height=d?d+"px":"0px";document.documentMode&&8>document.documentMode?(a.frameBorder=0,a.margin=0,a.marginWidth=0,a.marginHeight=0,a.scrolling="no"):(a.setAttribute("scrolling","no"),a.setAttribute("marginwidth","0"),a.setAttribute("marginheight","0"),a.setAttribute("frameborder","0"));return a};
EBP.Light.Infra.writeToFriendlyIframe=function(a,b,c){var c=this.isDefined(c)?c:!1,d;d=a.contentWindow?a.contentWindow.document:a.contentDocument&&a.contentDocument.document?a.contentDocument.document:a.contentDocument;d.open().write(b);c&&setTimeout(function(){d.close()},1E3)};
EBP.Light.Infra.createUnfriendlyIframe=function(a,b){if(b&&!EBP.Light.Infra.isPageLoaded())this.logger&&this.logger.info("Adding unfriendly iframe in sync mode, url: "+a),document.write('<iframe src="'+a+'" style="display:none;width:0px;height:0px"></iframe>');else{this.logger&&this.logger.info("Adding unfriendly iframe in async mode, url: "+a);var c=document.createElement("iframe");c.setAttribute("src",a);c.style.display="none";EBP.Light.Infra.addChildToPage(c)}};
EBP.Light.Infra.getTopLevelReferrer=function(a){var b=null;try{a.top&&a.top.document&&a.top.document.referrer&&(b=a.top.document.referrer.toString())}catch(c){}return b};
EBP.Light.Infra.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array||!(a instanceof Object)&&"[object Array]"==Object.prototype.toString.call(a)||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&("[object Function]"==Object.prototype.toString.call(a)||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};EBP.Light.Logger=function(a){this._level=a;this.startNestingGroupNames=[];this.endNestingGroupNames=[]};EBP.Light.Logger.DebugMode="mmdebug";EBP.Light.Logger.LoggerLevels={NONE:0,ERROR:1,INFO:2,WARN:3,DEBUG:4};
EBP.Light.Logger.prototype={setLevel:function(a){this._level=a},timestamp:!1,debug:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.DEBUG,arguments)},info:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.INFO,arguments)},warn:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.WARN,arguments)},error:function(a){this._reportToLog(EBP.Light.Logger.LoggerLevels.ERROR,arguments)},exception:function(a,b){var c="string"!==b?this._format("Exception in {0}. message: {1}",a,b.message):
this._format("Exception in: {0}. message: {1}",a,b);b.stack&&(c+=this._format(" stack: {0}",b.stack));this._reportToLog(EBP.Light.Logger.LoggerLevels.ERROR,[c])},startGroup:function(a){this._supportNesting()&&this.startNestingGroupNames.push(a)},endGroup:function(){this._supportNesting()&&0<this.endNestingGroupNames.length&&window.console.groupEnd(this.endNestingGroupNames.pop())},_consoleAvailable:function(){try{return void 0!==window&&void 0!==window.console}catch(a){return!1}},_supportNesting:function(){return this._consoleAvailable()?
void 0!==window.console.group:!1},_supportErrorMessage:function(){return void 0!==window.console.error},_supportInfoMessage:function(){return void 0!==window.console.info||void 0!==window.opera},_supportWarnMessage:function(){return void 0!==window.console.warn||void 0!==window.opera},_supportObjectView:function(){return void 0!==window.console.dir||void 0!==window.opera},_callConsoleFunction:function(a,b){var c=!1;switch(a){case EBP.Light.Logger.LoggerLevels.INFO:this._supportInfoMessage()&&(window.console.info(b),
c=!0);break;case EBP.Light.Logger.LoggerLevels.WARN:this._supportWarnMessage()&&(window.console.warn(b),c=!0);break;case EBP.Light.Logger.LoggerLevels.ERROR:this._supportErrorMessage()&&(consoleFunction=window.console.error(b),c=!0)}c||window.console.log(b)},_format:function(a){for(var b=1;b<arguments.length;b++)a=a.replace(RegExp("\\{"+(b-1)+"\\}","gi"),""+arguments[b]);return a},_getTimestamp:function(){if(this.timestamp)return EBP.Light.Infra.getTimestamp()},_reportToLog:function(a,b){if(this._level>=
a&&this._consoleAvailable()){var c=b[0];"[object String]"!==Object.prototype.toString.call(c)?this._supportObjectView()||(c=c.toString()):c=this._format.apply(null,b);this.timestamp&&"[object String]"===Object.prototype.toString.call(c)&&(c=this._getTimestamp()+": "+c);if(void 0===window.opera){for(;this.startNestingGroupNames.length;)window.console.group(this.startNestingGroupNames[0]),this.endNestingGroupNames.push(this.startNestingGroupNames.shift());this._callConsoleFunction(a,c)}else opera.postError(c)}}};
EBP="undefined"!=typeof EBP?EBP:{};EBP.Adaptors=EBP.Adaptors||{};EBP.Adaptors.WebAdaptor=function(){};
EBP.Adaptors.WebAdaptor.prototype={getDataFromRemoteServer:function(a,b,c,d,e){var d=void 0!=typeof d?d:!0,e=void 0!=typeof e?e:!1,h=function(){try{if(e){var a,d;a=document.createElement("div");a.innerHTML="<xml>"+g.responseText+"</xml>";document.body.appendChild(a);d=a.firstChild.XMLDocument;document.body.removeChild(a);b.call(c,d)}else b.call(c,g.responseText)}catch(f){b.call(c)}},f=!1;try{if(this._isXMLHttpRequestSupported()){var j=new XMLHttpRequest;j.open("GET",a,d);j.send();f=!0;if(d)j.onreadystatechange=
function(){4==j.readyState&&(200==j.status?b.call(c,e?j.responseXML:j.responseText):b.call(c))};else return b.call(c,e?j.responseXML:j.responseText)}else if(window.XDomainRequest)if(d){var g=new XDomainRequest;g?(g.onerror=function(){gEBMainWindow.EBP.log.error("XDomain request error");b.call(c)},g.ontimeout=function(){gEBMainWindow.EBP.log.error("XDomain request timeout");b.call(c)},g.onload=h,g.open("get",a),g.send(),f=!0):gEBMainWindow.EBP.log.error("XDomain request failed")}else gEBMainWindow.EBP.log.warn("XDomain request does not support sync mode")}catch(n){gEBMainWindow.EBP.log.error("Adaptor.getDataFromRemoteServer",
n),f=!1}return f},_isXMLHttpRequestSupported:function(){var a=window.XMLHttpRequest?new XMLHttpRequest:null;return a&&"boolean"==typeof a.withCredentials},isMobile:function(a){var b=!1;if(a==EBPreServing.DeviceTypes.MOBILE||a==EBPreServing.DeviceTypes.TABLET)b=!0;return b}};var EBPreServing=window.EBPreServing||{};EBPreServing.BandWidthDetection=function(){};
EBPreServing.BandWidthDetection.prototype={checked:!1,checking:!1,speed:0,_adjustment:0.75,_images:[],_loaded:0,_maxSpeed:2E3,_tuneResults:[[150,1.6],[300,1.4],[500,1.3],[800,1],[1E3,0.9],[2E3,0.8]],initImages:function(a,b){this._images=[{path:unescape(a+b+"micro.gif"),bytes:51,start:null,end:null},{path:unescape(a+b+"micro.gif"),bytes:51,start:null,end:null},{path:unescape(a+b+"bw_image.png"),bytes:43677,start:null,end:null}]},_loadImage:function(a){this._images[a].start=(new Date).getTime();var b=
new Image,c=Math.random();b.onload=function(){gEBMainWindow.EBP.ebBW._imageLoaded(a)};b.src=this._images[a].path+"?rnd="+c},_imageLoaded:function(a){this._images[a].end=(new Date).getTime();this._loaded++;this._loaded==this._images.length&&this._calculateSpeed()},listeners:[],addListener:function(a){this.listeners[gEBMainWindow.EBP.ebBW.listeners.length]=a},_dispatchEvent:function(){for(var a=0;a<this.listeners.length;a++)this.listeners[a]&&(this.listeners[a](),this.listeners[a]=null)},_calculateSpeed:function(){var a=
Math.min(this._images[0].end-this._images[0].start,this._images[1].end-this._images[1].start),b=this._images[2].end-this._images[2].start,c=b,d=this._images[2].bytes;b>a&&(c=b-a,d-=this._images[0].bytes);this.speed=Math.round(8*(d/(c/1E3)/1024))*this._adjustment;if(Infinity==this.speed||this.speed>=this._maxSpeed)this.speed=this._maxSpeed;else{for(a=0;a<this._tuneResults.length&&this.speed>this._tuneResults[a][0];a++);this.speed=Math.min(this._maxSpeed,Math.round(this.speed*this._tuneResults[a][1]))}this.checked=
!0;this.checking=!1;this._dispatchEvent()},init:function(){this.checking=!0;this._loadImage(0);this._loadImage(1);this._loadImage(2);var a=this;setTimeout(function(){if(!a.checked)a.speed=56,a.checked=!0,a.checking=!1,a._dispatchEvent()},5E3)}};function p(a){return function(){return a}}
(function(){function a(a){try{if(navigator.plugins&&navigator.plugins.length)for(var b=0;b<navigator.plugins.length;b++){var c=navigator.plugins[b];if(0<=c.name.indexOf(a))return c.name+(c.description?"|"+c.description:"")}}catch(d){}return""}function b(b){var o=new Date,w=new Date,g=[p("TF1"),p("015"),function(){return ScriptEngineMajorVersion()},function(){return ScriptEngineMinorVersion()},function(){return ScriptEngineBuildVersion()},function(){return f("{7790769C-0471-11D2-AF11-00C04FA35D02}")},
function(){return f("{89820200-ECBD-11CF-8B85-00AA005B4340}")},function(){return f("{283807B5-2C60-11D0-A31D-00AA00B92C03}")},function(){return f("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return f("{44BBA848-CC51-11CF-AAFA-00AA00B6015C}")},function(){return f("{9381D8F2-0288-11D0-9501-00AA00B911A5}")},function(){return f("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return f("{5A8D6EE0-3E18-11D0-821E-444553540000}")},function(){return f("{89820200-ECBD-11CF-8B85-00AA005B4383}")},
function(){return f("{08B0E5C0-4FCB-11CF-AAA5-00401C608555}")},function(){return f("{45EA75A0-A269-11D1-B5BF-0000F8051515}")},function(){return f("{DE5AED00-A4BF-11D1-9948-00C04F98BBC9}")},function(){return f("{22D6F312-B0F6-11D0-94AB-0080C74C7E95}")},function(){return f("{44BBA842-CC51-11CF-AAFA-00AA00B6015B}")},function(){return f("{3AF36230-A269-11D1-B5BF-0000F8051515}")},function(){return f("{44BBA840-CC51-11CF-AAFA-00AA00B6015C}")},function(){return f("{CC2A9BA0-3BDD-11D0-821E-444553540000}")},
function(){return f("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}")},function(){return eval("navigator.appCodeName")},function(){return eval("navigator.appName")},function(){return eval("navigator.appVersion")},function(){return h(["navigator.productSub","navigator.appMinorVersion"])},function(){return eval("navigator.browserLanguage")},function(){return eval("navigator.cookieEnabled")},function(){return h(["navigator.oscpu","navigator.cpuClass"])},function(){return eval("navigator.onLine")},function(){return eval("navigator.platform")},
function(){return eval("navigator.systemLanguage")},function(){return eval("navigator.userAgent")},function(){return h(["navigator.language","navigator.userLanguage"])},function(){return eval("document.defaultCharset")},function(){return eval("document.domain")},function(){return eval("screen.deviceXDPI")},function(){return eval("screen.deviceYDPI")},function(){return eval("screen.fontSmoothingEnabled")},function(){return eval("screen.updateInterval")},function(){return 0!==Math.abs(n-m)},function(){return d(o)},
p("@UTC@"),function(){var a=0,a=0;d(o)&&(a=Math.abs(n-m));return-(o.getTimezoneOffset()+a)/60},function(){return(new Date(2005,5,7,21,33,44,888)).toLocaleString()},function(){return eval("screen.width")},function(){return eval("screen.height")},function(){return l.Acrobat},function(){return l.Flash},function(){return l.QuickTime},function(){return l["Java Plug-in"]},function(){return l.Director},function(){return l.Office},p("@CT@"),function(){return n},function(){return m},function(){return o.toLocaleString()},
function(){return eval("screen.colorDepth")},function(){return eval("window.screen.availWidth")},function(){return eval("window.screen.availHeight")},function(){return eval("window.screen.availLeft")},function(){return eval("window.screen.availTop")},function(){return a("Acrobat")},function(){return a("Adobe SVG")},function(){return a("Authorware")},function(){return a("Citrix ICA")},function(){return a("Director")},function(){return a("Flash")},function(){return a("MapGuide")},function(){return a("MetaStream")},
function(){return a("PDFViewer")},function(){return a("QuickTime")},function(){return a("RealOne")},function(){return a("RealPlayer Enterprise")},function(){return a("RealPlayer Plugin")},function(){return a("Seagate Software Report")},function(){return a("Silverlight")},function(){return a("Windows Media")},function(){return a("iPIX")},function(){return a("nppdf.so")},function(){var a=document.createElement("span");a.innerHTML="&nbsp;";a.style.position="absolute";a.style.left="-9999px";document.body.appendChild(a);
var b=a.offsetHeight;document.body.removeChild(a);return b}];e();for(var k="",q=0;q<g.length;q++){b&&(k+=c(g[q].toString(),'"',"'",!0),k+="=");var j;try{j=g[q](this)}catch(x){j=""}k+=b?j:escape(j);k+=";";b&&(k+="\\n")}k=c(k,escape("@UTC@"),(new Date).getTime());k=c(k,escape("@CT@"),(new Date).getTime()-w.getTime());return window.f1b5?window.f1b5(k):k}function c(a,b,c,d){"boolean"!==typeof d&&(d=!1);for(var e=!0,f;0<=(f=a.indexOf(b))&&(d||e);)a=a.substr(0,f)+c+a.substr(f+b.length),e=!1;return a}function d(a){var b=
Math.min(n,m);return 0!==Math.abs(n-m)&&a.getTimezoneOffset()===b}function e(){for(var a="Acrobat,Flash,QuickTime,Java Plug-in,Director,Office".split(","),b=0;b<a.length;b++){var c=a[b],d=l,e=c,f=c,c="";try{if(navigator.plugins&&navigator.plugins.length)for(var h=RegExp(f+".* ([0-9._]+)"),f=0;f<navigator.plugins.length;f++){var g=h.exec(navigator.plugins[f].name);null===g&&(g=h.exec(navigator.plugins[f].description));g&&(c=g[1])}else if(window.ActiveXObject&&t[f])try{var j=new ActiveXObject(t[f][0]),
c=t[f][1](j)}catch(n){c=""}}catch(m){c=m.message}d[e]=c}}function h(a){for(var b=0;b<a.length;b++)try{var c=eval(a[b]);if(c)return c}catch(d){}return""}function f(a){var b="";try{"undefined"!==typeof g.a.getComponentVersion&&(b=g.a.getComponentVersion(a,"ComponentID"))}catch(c){a=c.message.length,b=escape(c.message.substr(0,40<a?40:a))}return b}function j(a){function b(a){d=d<<a[0]|a[1];for(e+=a[0];6<=e;)a=d>>e-6&63,c+=r.substring(a,a+1),e-=6,d^=a<<e}var c="",d=0,e=0;b([6,(a.length&7)<<3|0]);b([6,
a.length&56|1]);for(var f=0;f<a.length;f++){if(void 0==u[a.charCodeAt(f)])return;b(u[a.charCodeAt(f)])}b(u[0]);0<e&&b([6-e,0]);return c}var g={},n=(new Date(2005,0,15)).getTimezoneOffset(),m=(new Date(2005,6,15)).getTimezoneOffset(),l=[],t={Flash:["ShockwaveFlash.ShockwaveFlash",function(a){return a.getVariable("$version")}],Director:["SWCtl.SWCtl",function(a){return a.ShockwaveVersion("")}]};try{g.a=document.createElement("span"),"undefined"!==typeof g.a.addBehavior&&g.a.addBehavior("#default#clientCaps")}catch(y){}var l=
{},u={1:[4,15],110:[8,239],74:[8,238],57:[7,118],56:[7,117],71:[8,233],25:[8,232],101:[5,28],104:[7,111],4:[7,110],105:[6,54],5:[7,107],109:[7,106],103:[9,423],82:[9,422],26:[8,210],6:[7,104],46:[6,51],97:[6,50],111:[6,49],7:[7,97],45:[7,96],59:[5,23],15:[7,91],11:[8,181],72:[8,180],27:[8,179],28:[8,178],16:[7,88],88:[10,703],113:[11,1405],89:[12,2809],107:[13,5617],90:[14,11233],42:[15,22465],64:[16,44929],"0":[16,44928],81:[9,350],29:[8,174],118:[8,173],30:[8,172],98:[8,171],12:[8,170],99:[7,84],
117:[6,41],112:[6,40],102:[9,319],68:[9,318],31:[8,158],100:[7,78],84:[6,38],55:[6,37],17:[7,73],8:[7,72],9:[7,71],77:[7,70],18:[7,69],65:[7,68],48:[6,33],116:[6,32],10:[7,63],121:[8,125],78:[8,124],80:[7,61],69:[7,60],119:[7,59],13:[8,117],79:[8,116],19:[7,57],67:[7,56],114:[6,27],83:[6,26],115:[6,25],14:[6,24],122:[8,95],95:[8,94],76:[7,46],24:[7,45],37:[7,44],50:[5,10],51:[5,9],108:[6,17],22:[7,33],120:[8,65],66:[8,64],21:[7,31],106:[7,30],47:[6,14],53:[5,6],49:[5,5],86:[8,39],85:[8,38],23:[7,
18],75:[7,17],20:[7,16],2:[5,3],73:[8,23],43:[9,45],87:[9,44],70:[7,10],3:[6,4],52:[5,1],54:[5,0]},v="%20,;;;,%3B,%2C,und,fin,ed;,%28,%29,%3A,/53,ike,Web,0;,.0,e;,on,il,ck,01,in,Mo,fa,00,32,la,.1,ri,it,%u,le".split(","),r=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz";window.f1b5=function(a){for(var b=a,c=0;v[c];c++)b=b.split(v[c]).join(String.fromCharCode(c+1));b=j(b);if(void 0==b)return a;for(var c=65535,d=0;d<a.length;d++)c=(c>>>8|c<<8)&65535,c^=a.charCodeAt(d)&255,c^=(c&255)>>
4,c^=c<<12&65535,c^=(c&255)<<5&65535;c&=65535;a=""+r.charAt(c>>>12);a+=r.charAt(c>>>6&63);a+=r.charAt(c&63);return b+a};g.collect=function(a){try{if(!a)return b();var c;a:{var d;try{d=document.getElementById(a)}catch(e){}if(null===d||"undefined"===typeof d)try{d=document.getElementsByName(a)[0]}catch(f){}if(null===d||"undefined"===typeof d)for(var g=0;g<document.forms.length;g++)for(var h=document.forms[g],j=0;j<h.elements.length;j++){var l=h[j];if(l.name===a||l.id===a){c=l;break a}}c=d}if(null!==
c)try{c.value=b()}catch(m){c.value=escape(m.message)}}catch(n){}};window.fortyone=g;var s=navigator.userAgent.toLowerCase();"Gecko"===navigator.product&&2>=parseInt(s.substring(s.indexOf("rv:")+3,s.indexOf(")",s.indexOf("rv:")+3)).split(".")[0])&&window.fortyone.collect()})();var EBUidCache=window.EBUidCache||{};
EBUidCache.getUserId=function(a){gEBMainWindow.EBP=gEBMainWindow.EBP||{};var b=gEBMainWindow.ebUserIdGuid?gEBMainWindow.ebUserIdGuid:null;if(!gEBMainWindow.EBP.EBUidCache)gEBMainWindow.EBP.EBUidCache=new EBUidCache.Mgr,b=gEBMainWindow.EBP.EBUidCache.handleCacheUserIdentification(a);return b};EBUidCache.Mgr=function(){};
EBUidCache.Mgr.prototype={handleCacheUserIdentification:function(a){var b=null;this.isSupported(a.dt)&&(b=gEBMainWindow.EBP.adaptor.getDataFromRemoteServer(this.buildURL(a),this.handleServerResponse,this,!1));return b},handleServerResponse:function(a,b){if(!b&&typeof(void 0!=a))try{return(new Function(a))(),gEBMainWindow.ebUserIdGuid}catch(c){}return null},buildURL:function(a){return a.ebPtcl+a.bs+"/Serving?cn=cacheuser"},isSupported:function(a){return gEBMainWindow.EBP.adaptor.isMobile(a)}};
EBPreServing.ResponseType={GET:0,POST:1};EBPreServing.ProvidersEnum=["AdTruth","EBUidCache"];EBPreServing.UserIdProvider=function(){this._providers={};this._registerProviders()};
EBPreServing.UserIdProvider.prototype={_registerProviders:function(){this.registerProvider("AdTruth","ATData","fortyone.collect",!0,!1);this.registerProvider("EBUidCache","cuid","EBUidCache.getUserId",!0,!0)},registerProvider:function(a,b,c,d,e){if(this._providers[a])gEBMainWindow.EBP.log.warn(a+" provider already exist, provider not registered!");else{var h=this._verifyProviderCallbackFunc(c);h?(gEBMainWindow.EBP.log.info("Registering "+a+" provider"),this._providers[a]={tokenName:b,funcName:c,func:h,
id:null,shouldCache:d,sendData:e}):gEBMainWindow.EBP.log.info("Could not resolve "+a+" handler function name")}},_generateUserIds:function(a){for(var b=a.uip,c=0;c<b.length;c++){var d=b[c],e=this._providers[d],h=null;if(e)if(!e.id||!e.shouldCache){gEBMainWindow.EBP.log.info("calculating ID with "+d);try{h=e.sendData?e.func.apply(null,[a]):e.func.apply()}catch(f){h=null,gEBMainWindow.EBP.log.error("Got exception during "+d+" ID calculation: "+f)}e.id=h}else gEBMainWindow.EBP.log.info("Using "+d+" cached ID")}},
getUserIds:function(a,b){var c="";a.uip=this._getValidProviderNames(a.uip);this._generateUserIds(a);return c=this._formatResponse(a.uip,b)},_formatResponse:function(a,b){var c="";switch(b){default:case EBPreServing.ResponseType.GET:for(var d=0;d<a.length;d++){var e=this._providers[a[d]];e.id&&(c+="&"+e.tokenName+"="+e.id)}case EBPreServing.ResponseType.POST:}return c},_verifyProviderCallbackFunc:function(a){for(var b=a.split("."),c=null,d=window,e=0,h=b.length;e<h;e++){var f=b[e];if(void 0!==d[f]&&
(d=d[f],e==h-1&&"function"==typeof d)){gEBMainWindow.EBP.log.debug("Resolved function "+a);c=d;break}}return c},_getValidProviderNames:function(a){var b=[];if("array"==EBP.Light.Infra.typeOf(a))for(var c=0;c<a.length;c++)"number"==EBP.Light.Infra.typeOf(a[c])?b[b.length]=EBPreServing.ProvidersEnum[a[c]-1]:gEBMainWindow.EBP.log.error("error in _getValidProviderNames in UserIdentification.js - uip should include only numbers");return b}};EBPreServing=window.EBPreServing||{};
EBPreServing.ServingState={script:"SCRIPT",friendlyIframe:"FRIENDLY_IFRAME",unfriendlyIframe:"IFRAME"};
EBPreServing.SecretTags={gEbBAd:"gEbBAd",gEbAd:"gEbAd",gfEbForceStreaming:"gfEbForceStreaming",gEbEyeDivRefElement:"gEbEyeDivRefElement",gfEbUseCompression:"gfEbUseCompression",gfEbRemoveScroll:"gfEbRemoveScroll",gfEbUseMozHideIframe:"gfEbUseMozHideIframe",gnEbLowBWLimit:"gnEbLowBWLimit",gstrEbDisplayPos:"gstrEbDisplayPos",strPage:"strPage",gfEbChangeRelativeElements:"gfEbChangeRelativeElements",gfEbInlineBanner:"gfEbInlineBanner",gstrEbPreLoadScripts:"gstrEbPreLoadScripts",gfEbExpBanerIM:"gfEbExpBanerIM",
gstrEbIframeLocation:"gstrEbIframeLocation",gstrEbDomain:"gstrEbDomain",gnEbMinZIndex:"gnEbMinZIndex",gfEbCacheResources:"gfEbCacheResources",gfEbUseHTTPS:"gfEbUseHTTPS"};EBPreServing.DeviceTypes={DESKTOP:0,MOBILE:1,TABLET:2,UNKNOWN:3};EBPreServing=window.EBPreServing||{};
EBPreServing.getTopWindow=function(){var a=window;a.EBservingMode=EBPreServing.ServingState.script;try{for(;a.self!==a.parent;){var b=null;try{b=a.parent.location.hostname}catch(c){}if(a.location.hostname===b)a=a.parent,a.EBservingMode=EBPreServing.ServingState.friendlyIframe;else{a.EBservingMode=EBPreServing.ServingState.unfriendlyIframe;break}}}catch(d){}return a};
EBPreServing._startEBPreservingFlow=function(){_updateFocused=function(){gEBMainWindow.EBP.focused=!0;try{window.removeEventListener?(window.removeEventListener("focus",_updateFocused,!1),window.document.removeEventListener("focusin",_updateFocused,!1)):window.detachEvent&&(window.detachEvent("onfocus",_updateFocused),window.document.detachEvent("onfocusin",_updateFocused))}catch(a){}};registerSpecialBrowserEvents=function(){gEBMainWindow.EBP.focused=!1;window.addEventListener?(window.addEventListener("focus",
_updateFocused,!1),window.document.addEventListener("focusin",_updateFocused,!1)):window.attachEvent&&(window.attachEvent("onfocus",_updateFocused),window.document.attachEvent("onfocusin",_updateFocused,!1))};if(gEBMainWindow.EBP.downloadMgr)try{gEBMainWindow.EBP.downloadMgr._testFreedScript()}catch(a){gEBMainWindow.EBP.downloadMgr=new EBPreServing.DownloadManager,gEBMainWindow.EBP.UIdProviderMgr=new EBPreServing.UserIdProvider}else gEBMainWindow.EBP.downloadMgr=new EBPreServing.DownloadManager;registerSpecialBrowserEvents();
if(!gEBMainWindow.EBP.downloadMgr.ebSync.checkedIfPageLoaded)gEBMainWindow.EBP.downloadMgr.ebSync.checkedIfPageLoaded=!0,gEBMainWindow.EBP.downloadMgr.checkPageLoaded(gEBMainWindow,gEBMainWindow.EBP.downloadMgr.updatePageLoaded);!gEBMainWindow.EBP.downloadMgr.ebSync.donwloadServerReq&&!gEBMainWindow.EBP.downloadMgr.ebSync.loadingCustomScript&&(gEBMainWindow.EBP.log.debug("Start serving request process"),gEBMainWindow.EBP.downloadMgr.initServerReq())};
EBPreServing._addSecretTags=function(){var a=null,b;for(b in EBPreServing.SecretTags){var c=EBPreServing.SecretTags[b];c in window&&(a||(a={}),a[c]=window[c])}return a};EBPreServing.DownloadManager=function(){gEBMainWindow.EBP.log.debug("DownloadManager.Constructor");if(!this.ebSync)this.ebSync={donwloadServerReq:!1,divId:0,currDoc:document,async:null,checkedIfPageLoaded:!1,loadingCustomScript:!1,placementIdObj:{}}};
EBPreServing.DownloadManager.prototype={ebSync:null,bigScriptObj:{},customScriptArr:[],initServerReq:function(){gEBMainWindow.EBP.log.startGroup("DownloadManager.initServerReq");try{var a=gEBMainWindow.EBP.ebTags[0];if(a)if("undefined"!=typeof a.sms&&""!=a.sms&&"/"!=a.sms[a.sms.length-1]&&(a.sms+="/"),this.ebSync.async=this.isAsyncMode(a),this.setAdditionalTagTokens(a),this.ebSync.placementIdObj[a.placementId]={},this.ebSync.placementIdObj[a.placementId].async=this.ebSync.async,a.bandWidth){var b=
this.handleBandwidthDetection(a);b||this.loadServerRequest()}else this.loadServerRequest();else gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - tag doesn't exist!!!");if(0<gEBMainWindow.EBP.ebTags.length&&!this.ebSync.donwloadServerReq&&!this.ebSync.loadingCustomScript&&!b){var c=this;setTimeout(function(){c.initServerReq()},0)}gEBMainWindow.EBP.log.endGroup()}catch(d){gEBMainWindow.EBP.log.exception("DownloadManager.initServerReq",d)}},loadServerRequest:function(){if(this.ebSync.loadingCustomScript){gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Currently loading custom script");
var a=this;this._customScriptServerRequestCallBack=function(){try{a.initServerReq()}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager._customScriptServerRequestCallBack",c)}}}else{this.ebSync.donwloadServerReq=!1;try{currTag=gEBMainWindow.EBP.ebTags.shift()}catch(b){0<gEBMainWindow.EBP.ebTags.length&&(currTag=gEBMainWindow.EBP.ebTags[0]);for(i=0;i<gEBMainWindow.EBP.ebTags.length-1;i++)gEBMainWindow.EBP.ebTags[i]=gEBMainWindow.EBP.ebTags[i+1];gEBMainWindow.EBP.ebTags.length--}currTag&&(this.setCurrTag(currTag),
this.handleCurrTag(currTag))}},handleCurrTag:function(a){this.ebSync.placementIdObj[a.placementId].async?(gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Start Async Client process"),this.handleAsyncTag(a)):(gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Start Sync Client process"),gEBMainWindow.EBservingMode===EBPreServing.ServingState.script&&a.loadInIframe?this.handleSyncTag(a):a.currDoc.write("<script src="+a.partialRequest+"><\/script>"))},setCurrTag:function(a){var b=
EBP.Light.Infra.getRandomNumber();a.ebRand=b;a.partialRequest+="&rand="+b;a.bandWidth&&gEBMainWindow.EBP.ebBW.checked&&56!=gEBMainWindow.EBP.ebBW.speed&&(a.partialRequest+="&BWVal="+(a.bwMult?a.bwMult*gEBMainWindow.EBP.ebBW.speed:gEBMainWindow.EBP.ebBW.speed)+"&BWDate=0");if(gEBMainWindow.EBservingMode&&gEBMainWindow.EBservingMode===EBPreServing.ServingState.unfriendlyIframe){if((b=EBP.Light.Infra.getAddInEyeDomain(gEBMainWindow,a.ebPtcl))&&""!=b)a.partialRequest+="&dm="+b;a.partialRequest=a.partialRequest.replace("ifrm=2",
"ifrm=1")}a.partialRequest+="&secCall=1";a.partialRequest=a.collectURL?a.partialRequest+"&vurl="+this.getVerificationUrl(a):a.partialRequest;a.partialRequest+=gEBMainWindow.EBP.UIdProviderMgr.getUserIds(a,EBPreServing.ResponseType.GET);a.loadInIframe=a.lii?a.lii:!1},handleBandwidthDetection:function(a){var b=!1;if(!gEBMainWindow.EBP.ebBW)gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Create bandWidthDetector object (ebBW)"),gEBMainWindow.EBP.ebBW=new EBPreServing.BandWidthDetection;
if("undefined"!=typeof EBG&&"undefined"!=typeof EBG.BWDetection&&EBG.BWDetection.checked)gEBMainWindow.EBP.ebBW.speed=EBG.BWDetection.speed,gEBMainWindow.EBP.ebBW.checked=!0;if(!gEBMainWindow.EBP.ebBW.checked&&!gEBMainWindow.EBP.ebBW.checking){b="https:"==a.currDoc.location.protocol?"https://":"http://";a.ebPtcl="undefined"==typeof a.ebPtcl?b:a.ebPtcl;gEBMainWindow.EBP.ebBW.initImages(a.ebPtcl,a.sms);var c=this;gEBMainWindow.EBP.ebBW.addListener(function(){c.initServerReq()});gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Start Band Width detection");
gEBMainWindow.EBP.ebBW.init();b=!0}gEBMainWindow.EBP.ebBW.checking&&(gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Still detecting Band Width"),b=!0);return b},handleAsyncTag:function(a){this.ebSync.divId=a.containerId;gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - Send Server Request");this._customScriptServerRequestCallBack=null;this.ebSync.donwloadServerReq=!0;var b={};b.currDoc=a.currDoc?a.currDoc:document;b.containerId=a.containerId;var c=this;this.scriptTag(a.partialRequest,
function(){c.ebSync.donwloadServerReq=!1;c.initServerReq()},b)},handleSyncTag:function(a){var b=this.setIfrmInRequest(a.partialRequest);if(b!==a.partialRequest&&b.length>a.partialRequest.length)a.partialRequest=b;b=EBP.Light.Infra.createFriendlyIframe(a.currDoc,a.ebRand,a.width,a.height);a.onLoadHandled=!1;var c={iframeContainer:b,myIfrmSrc:"<!DOCTYPE html><html><head></head><body><script type='text/javascript''>var inDapIF = true; "+this._translateSecretTags(a.tagsObj)+"<\/script><script src='"+
a.partialRequest+"'><\/script></body></html>",tag:a},a=a.currDoc.getElementById(a.containerId),c=this.bindTagToCallback(function(){if(!this.tag.onLoadHandled)EBP.Light.Infra.writeToFriendlyIframe(this.iframeContainer,this.myIfrmSrc,!0),this.tag.onLoadHandled=!0},c);EBP.Light.Infra.addChildToPage(b,a,"load",c)},bindTagToCallback:function(a,b){return a.bind?a.bind(b):function(a,b){return function(){return a.apply(b,arguments)}}(a,b)},_translateSecretTags:function(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&
("object"!=typeof a[c]?b+="var "+this._getTagValue(c,a[c]):(b+=" var "+c+" =  new Object();",b+=this._stringnifyObj(c,a[c],"")));return b},_stringnifyObj:function(a,b,c){var d="",e;for(e in b)b.hasOwnProperty(e)&&(d=a+"."+e,"object"!=typeof b[e]?c+=this._getTagValue(d,b[e]):(c+=d+"= new Object();",c=this._stringnifyObj(d,b[e],c)));return c},_getTagValue:function(a,b){return"string"==typeof b?a+" = unescape('"+escape(b)+"');":a+" ="+b+";"},setIfrmInRequest:function(a){var b=a.indexOf("&ifrm");if(-1!=
b){if(-1==a.indexOf("&ifrm=-1"))var c="",c=a.substr(0,b),a=c=c+"&ifrm=-1"+currTag.partialRequest.substr(b+7,a.length)}else a+="&ifrm=-1";return a},setAdditionalTagTokens:function(a){if("undefined"==typeof a.placementId){var b=a.partialRequest.split("&");requestObj={};for(var c=1;c<b.length;c++)b[c]=b[c].split("="),requestObj[[b[c][0]]]=b[c][1];a.placementId=requestObj.pli;a.width=requestObj.w;a.height=requestObj.h}},getVerificationUrl:function(a){try{var b="";"undefined"!=typeof a.vurl&&""!=a.vurl?
b=a.vurl:(a=gEBMainWindow,b=a.EBservingMode==EBPreServing.ServingState.unfriendlyIframe?a.document.referrer:a.location.href);return b=escape(b)}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager.getUrl",c)}},isAsyncMode:function(a){gEBMainWindow.EBP.log.debug("DownloadManager.isAsyncMode ");try{return a.asyncMode||a.bandWidth}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager.isAsyncMode",b)}},reportImg:function(a){gEBMainWindow.EBP.log.debug("DownloadManager.reportImg ");try{(new Image).src=
a}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager.reportImg",b)}},scriptTag:function(a,b,c){gEBMainWindow.EBP.log.startGroup("DownloadManager.scriptTag");try{var d=c&&c.currDoc?c.currDoc:document,e=EBP.Light.Infra.createScriptElement(d,"script","text/"+(a.type||"javascript"),a.src||a);e.onreadystatechange=e.onload=function(){var a=e.readyState;if("function"==typeof b&&!b.done&&(!a||/loaded|complete/.test(a)))b.done=!0,b(c)};d=c&&c.currDoc?c.currDoc:document;if(!c||!c.containerId)EBP.Light.Infra.addScriptElement(e);
else{var h=d.getElementById(c.containerId);EBP.Light.Infra.addScriptElement(e,h)}gEBMainWindow.EBP.log.endGroup()}catch(f){gEBMainWindow.EBP.log.exception("DownloadManager.scriptTag",f)}},checkPageLoaded:function(a,b){gEBMainWindow.EBP.log.startGroup("DownloadManager.checkPageLoaded");try{var c=!1,d=!0,e=a.document,h=e.documentElement,f=e.addEventListener?"addEventListener":"attachEvent",j=e.addEventListener?"removeEventListener":"detachEvent",g=e.addEventListener?"":"on";gEBMainWindow.EBP.init=function(d){if(!("readystatechange"==
d.type&&"complete"!=e.readyState)&&(("load"==d.type?a:e)[j](g+d.type,gEBMainWindow.EBP.init,!1),!c&&(c=!0)))b.call(a,d.type||d)};gEBMainWindow.EBP.poll=function(){try{h.doScroll("left")}catch(a){setTimeout(gEBMainWindow.EBP.poll,50);return}gEBMainWindow.EBP.init("gEBMainWindow.EBP.poll")};if("complete"==e.readyState)b.call(a,"lazy");else{if(e.createEventObject&&h.doScroll){try{d=!a.frameElement}catch(n){}d&&gEBMainWindow.EBP.poll()}e[f](g+"DOMContentLoaded",gEBMainWindow.EBP.init,!1);e[f](g+"readystatechange",
gEBMainWindow.EBP.init,!1);a[f](g+"load",gEBMainWindow.EBP.init,!1)}gEBMainWindow.EBP.log.endGroup()}catch(m){gEBMainWindow.EBP.log.exception("DownloadManager.checkPageLoaded",m)}},updatePageLoaded:function(){gEBMainWindow.EBP.log.debug("DownloadManager.isPageLoaded");try{gEBMainWindow.EBP.isPageLoaded=!0}catch(a){gEBMainWindow.EBP.log.exception("DownloadManager.isPageLoaded",a)}},loadBigScript:function(a,b,c,d){gEBMainWindow.EBP.log.startGroup("DownloadManager.loadBigScript");try{if(window.gstrAdPrefix){var e=
window.gstrAdPrefix;-1==b.indexOf(e)&&(b=b.replace(/Ad_/,e))}if(this.ebSync.loadingCustomScript){gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: loading cutom script: {0} ",c);var h=this;this._customScriptBigScriptCallBack=function(){try{h.loadBigScript(a,b,c,d),"function"==typeof h._customScriptServerRequestCallBack&&h._customScriptServerRequestCallBack()}catch(e){gEBMainWindow.EBP.log.exception("DownloadManager._customScriptBigScriptCallBack"+e)}}}else{this._customScriptBigScriptCallBack=
null;gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: loading {0} script",c);var f={};f.containerId=a?a:null;f.bigScriptSrc=b?b:null;f.scriptName=c?c:null;f.currDoc=d?d:document;e={containerId:a,currDoc:d};this.bigScriptObj[c]=this.bigScriptObj[c]||{};this.bigScriptObj[c].waitingToLoad=this.bigScriptObj[c].waitingToLoad||[];-1==this.indexOfArray(this.bigScriptObj[c].waitingToLoad,e)&&this.bigScriptObj[c].waitingToLoad.push(e);this.bigScriptObj[c].downloaded="undefined"!=typeof this.bigScriptObj[c].downloaded?
this.bigScriptObj[c].downloaded:!1;this.bigScriptObj[c].isFirst="undefined"!=typeof this.bigScriptObj[c].isFirst?this.bigScriptObj[c].isFirst:!0;this.bigScriptObj&&this.bigScriptObj[c]&&this.bigScriptObj[c].isFirst?(gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: First time loading {0} script",this.bigScriptObj[c]),this.bigScriptObj[f.scriptName].waitingToLoad.shift(),this.bigScriptObj[f.scriptName].isFirst=!1,h=this,this.scriptTag(b,function(){h._releaseWaitingRequests(f)},f)):(gEBMainWindow.EBP.log.debug("DownloadManager.loadBigScript: Script {0} was already downloaded",
this.bigScriptObj[c]),this.bigScriptObj[c].downloaded&&this._releaseWaitingRequests(f));gEBMainWindow.EBP.log.endGroup()}}catch(j){gEBMainWindow.EBP.log.exception("DownloadManager.loadBigScript",j)}},indexOfArray:function(a,b){gEBMainWindow.EBP.log.debug("DownloadManager.indexOfArrays");try{for(var c=0;c<a.length;c++)if(a[c]==b)return c;return-1}catch(d){gEBMainWindow.EBP.log.exception("DownloadManager.indexOfArray",d)}},loadCustomScript:function(a,b){gEBMainWindow.EBP.log.startGroup("DownloadManager.loadCustomScript");
try{var c={};c.currDoc="undefined"!=typeof b?b:document;if(0!=this.ebSync.divId)c.containerId=this.ebSync.divId;if("undefined"!=typeof a){for(var d=a.length-1;0<=d;d--)if(""==a[d]||"http://"==a[d].substr(0,7)&&"https://"==ebPtcl)gEBMainWindow.EBP.log.info("custom script "+a[d]+" will not be loaded since it is from not secured protocol while the ad runs from secured protocol"),a.splice(d,1);if(0<a.length)this.ebSync.loadingCustomScript=!0;c.CSArray=a;for(d=0;d<a.length;d++)"http"!=a[d].substr(0,4)&&
(a[d]=ebResourcePath+"CustomScripts/"+a[d]),this.customScriptArr[d]={},this.customScriptArr[d].cs=a[d],this.customScriptArr[d].loaded=!1;this.customScriptsLoader(c)}gEBMainWindow.EBP.log.endGroup()}catch(e){gEBMainWindow.EBP.log.exception("DownloadManager.loadCustomScript",e)}},customScriptsLoader:function(a){gEBMainWindow.EBP.log.startGroup("DownloadManager.customScriptsLoader");try{if("undefined"!=typeof a&&a.CSArray&&0<a.CSArray.length){var b=a.CSArray.pop();a.index=a.CSArray.length;var c=this,
d=parseInt(a.index);gEBMainWindow.EBP.log.debug("DownloadManager.customScriptsLoader - loading script # :  {0}",b);this.scriptTag(b,function(){c.handleCustomScriptsLoaded(a,d)},a);this.customScriptsLoader(a)}gEBMainWindow.EBP.log.endGroup()}catch(e){gEBMainWindow.EBP.log.exception("DownloadManager.customScriptsLoader",e)}},handleCustomScriptsLoaded:function(a,b){gEBMainWindow.EBP.log.startGroup("DownloadManager.handleCustomScriptsLoaded");try{if(this.customScriptArr&&this.customScriptArr[b])this.customScriptArr[b].loaded=
!0;if(this.areAllCustomScriptsLoaded())this.ebSync.loadingCustomScript=!1,"function"==typeof this._customScriptBigScriptCallBack&&this._customScriptBigScriptCallBack()}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager.handleCustomScriptsLoaded",c)}},areAllCustomScriptsLoaded:function(){gEBMainWindow.EBP.log.debug("DownloadManager.areAllCustomScriptsLoaded");try{if(this.customScriptArr){for(var a=0;a<this.customScriptArr.length;a++)if(!this.customScriptArr[a].loaded)return!1;return!0}}catch(b){gEBMainWindow.EBP.log.exception("DownloadManager.areAllCustomScriptsLoaded",
b)}},_customScriptBigScriptCallBack:null,_customScriptServerRequestCallBack:null,_releaseWaitingRequests:function(a){gEBMainWindow.EBP.log.startGroup("DownloadManager._releaseWaitingRequests");try{if("object"==typeof a&&"undefined"!=typeof a.scriptName&&(this.bigScriptObj[a.scriptName].downloaded=!0,this.bigScriptObj[a.scriptName]))for(;0<this.bigScriptObj[a.scriptName].waitingToLoad.length;){var b=this.bigScriptObj[a.scriptName].waitingToLoad.shift();gEBMainWindow.EBP.log.debug("Big script will be loaded into containderId {0}",
b.containerId);a.containerId=b.containerId;a.currDoc=b.currDoc;this.scriptTag(a.bigScriptSrc,function(){},a)}gEBMainWindow.EBP.log.endGroup()}catch(c){gEBMainWindow.EBP.log.exception("DownloadManager._releaseWaitingRequests",c)}},_testFreedScript:function(){return window&&Array?!0:!1}};gEBMainWindow=window.gEBMainWindow||EBPreServing.getTopWindow();gEBMainWindow.EBP=gEBMainWindow.EBP||{};gEBMainWindow.EBP.log=new EBP.Light.Logger(EBP.Light.Infra.getUrlParameter(EBP.Light.Logger.DebugMode)||0);
gEBMainWindow.EBP.adaptor=gEBMainWindow.EBP.adaptor||new EBP.Adaptors.WebAdaptor;gEBMainWindow.EBP.UIdProviderMgr=gEBMainWindow.EBP.UIdProviderMgr||new EBPreServing.UserIdProvider;gEBMainWindow.EBP.ebTags=gEBMainWindow.EBP.ebTags||[];
if(void 0!==window.ebNewTagArr)for(var i=0;i<ebNewTagArr.length;i++)if("undefined"==typeof ebNewTagArr[i].collected){ebNewTagArr[i].currDoc=document;ebNewTagArr[i].collected=!0;var tags=EBPreServing._addSecretTags();if(null!=tags)ebNewTagArr[i].tagsObj=tags;gEBMainWindow.EBP.ebTags[gEBMainWindow.EBP.ebTags.length]=ebNewTagArr[i]}
if(void 0!==window.ebNewTag&&"undefined"==typeof ebNewTag.collected){ebNewTag.currDoc=document;ebNewTag.collected=!0;tags=EBPreServing._addSecretTags();if(null!=tags)ebNewTag.tagsObj=tags;gEBMainWindow.EBP.ebTags[gEBMainWindow.EBP.ebTags.length]=ebNewTag}
try{var dispose=function(){try{if(gEBMainWindow.EBP.downloadMgr)gEBMainWindow.EBP.downloadMgr=null;if(gEBMainWindow.EBP.UIdProviderMgr)gEBMainWindow.EBP.UIdProviderMgr=null;if(gEBMainWindow.EBP.ebTags)gEBMainWindow.EBP.ebTags=null;if(gEBMainWindow.EBP.focused)gEBMainWindow.EBP.focused=null;if(gEBMainWindow.EBP.adaptor)gEBMainWindow.EBP.adaptor=null;EBPreServing=null}catch(a){}};window.addEventListener?window.addEventListener("unload",dispose,!1):window.attachEvent&&window.attachEvent("onunload",dispose)}catch(e$$46){}
gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - gEBMainWindow location:  {0}",gEBMainWindow.location.href);gEBMainWindow.EBP.log.debug("DownloadManager.initServerReq - curr document location:  {0}",document.location.href);0<gEBMainWindow.EBP.ebTags.length&&EBPreServing._startEBPreservingFlow();
