/*! ver:1418014201 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var m=!0,o=!1;window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/monitor1418014201",[],function(){return{sendLog:function(e){if(e=e.data&&e.data.monitorUrl){var g=new Image,f="log"+ +new Date;window[f]=g;g.onload=g.onerror=g.onabort=function(){g.onload=g.onerror=g.onabort=null;try{delete window[f]}catch(b){window[f]=void 0}};g.src=e}}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/template1418014201",[],function(){function e(e){var b={'"':"&quot;",">":"&gt;","<":"&lt;","&":"&amp;"};return e.replace(/[\"<>\&]/g,function(c){return b[c]})}var g=/\{(\w+)\:(\w+)\}/g;return{a:function(f,b){return f.replace(g,function(c,a,d){c=b[a];switch(d){case "number":c=+c||0;break;case "boolean":c=!!c;break;case "html":c=e(c)}return c})}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/material1418014201",["clb/template1418014201"],function(e){function g(b,c,a){if("string"===typeof b)return b;if(!b.type)return"";var d=f[b.type];return d?(b="string"===typeof d?e.a(d,b):d(b,c),a?b:"<!DOCTYPE html><body>"+b):""}var f={text:function(b){var c='<span style="word-wrap:break-word;"><a href="{clickUrl:string}" target="{target:string}" style="font-size:{size:number}{unit:string};color:{defaultColor:string};font-weight:{defaultBold:string};font-style:{defaultItalic:string};text-decoration:{defaultUnderline:string};"{events}>{text:string}</a></span>',
a=/\{events\}/;if(1===b.version)c=c.replace(a,"");else if(2===b.version)for(var c=c.replace(a," onmouseover=\"this.style.color='{hoverColor:string}';this.style.fontWeight='{hoverBold:string}';this.style.fontStyle='{hoverItalic:string}';this.style.textDecoration='{hoverUnderline:string}';\" onmouseout=\"this.style.color='{defaultColor:string}';this.style.fontWeight='{defaultBold:string}';this.style.fontStyle='{defaultItalic:string}';this.style.textDecoration='{defaultUnderline:string}';\""),a=["default",
"hover"],d=0;d<a.length;d++){var i=a[d],g=i+"Color",f=i+"Bold",j=i+"Italic",i=i+"Underline";b[g]="#"+b[g];b[f]=b[f]?"bold":"normal";b[j]=b[j]?"italic":"normal";b[i]=b[i]?"underline":"none"}return e.a(c,b)},image:'<a href="{clickUrl:string}" target="{target:string}"><img src="{src:string}" title="{title:html}" alt="{title:html}" border="0" height="{height:number}" width="{width:number}" /></a>',flash:function(b){b.file=b.hasLink?"cflash":"flash";b.imageClickUrl=b.clickUrl;b.hasLink||(b.clickUrl="");
return e.a('<script>var BD = BD || {};BD.MC = BD.MC || {};BD.MC.ADFlash = BD.MC.ADFlash || {};BD.MC.ADImg = BD.MC.ADImg || {};BD.MC.ADFlash.w = {width:number};BD.MC.ADFlash.h = {height:number};BD.MC.ADFlash.mu = "{src:string}";BD.MC.ADFlash.cu = "{clickUrl:string}";BD.MC.ADFlash.wm = {wmode:number};BD.MC.ADFlash.ct = "{clickTag:string}";BD.MC.ADImg.w = {imageWidth:number};BD.MC.ADImg.h = {imageHeight:number};BD.MC.ADImg.mu = "{imageSrc:string}";BD.MC.ADImg.cu = "{imageClickUrl:string}";BD.MC.ADImg.tw = "{target:string}";BD.MC.ADImg.flag = {backupImage:number};<\/script><script src ="http://cbjs.baidu.com/js/{file:string}.js"><\/script>',
b)},rich:function(b){return b.content},slide:function(b,c){for(var a=[],d=b.materials,i=0;i<d.length;i++){var f=d[i];"string"!==typeof f&&(f=g(f,c,m));a.push(f)}b.html="<div>"+a.join("</div><div>")+"</div>";b.width=c.width;b.height=c.height;return e.a('<div id="bd_ec_clb_asp" style="width:{width:number}px;height:{height:number}px;overflow:hidden;">{html:string}</div><script>(function(){var d = document;function G(id) { return d.getElementById(id); };var container = G("bd_ec_clb_asp");var pages = container.childNodes;var pl = 0;for (var i = 0; i < pages.length; i++) {if (pages[i].nodeType === 1) {pl++;}}var cp = 0;function showPage(pn) { pages[pn].style.display = ""; };function hidePages() {for (var i = 0; i < pl; i++) {pages[i].style.display = "none";}};function roll() {hidePages();showPage(cp);cp == (pages.length - 1) ? cp = 0 : cp++;};var autoRoll;function setRoll() { autoRoll = window.setInterval(function() { roll(); }, {interval:number});};roll();setRoll();container.onmouseover = function() { window.clearInterval(autoRoll); };container.onmouseout = function() {setRoll(); };})();<\/script>',
b)}};return{a:g}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/frame1418014201",["api"],function(e){function g(){var b=document.createElement("iframe"),a=o;b.src="about:blank";document.body.insertBefore(b,document.body.firstChild);try{a=!b.contentWindow.document}catch(d){a=m}document.body.removeChild(b);g=function(){return a};return a}function f(){var b=navigator.userAgent,a=b&&b.match(/iphone.*micromessenger/i)?m:o;f=function(){return a};return a}function b(){return g()?e.getConfig("domainPolicyFileUrl")||"/domain-policy.htm":
f()?e.getConfig("blankPolicyFileUrl")||"/blank-policy.htm":"about:blank"}e.defineOnce("BAIDU_DUP_CLB_renderFrame",function(c){var a=document.getElementById("baidu_clb_slot_iframe_"+c),d=e.getSlots(c);if(d)if(g()&&a.getAttribute("src",2)!==b())a.src=b();else if(d&&!d.status.finish)try{e.setStatus(c,"finish");var i=e.getInfo("#"+c).html;0>i.indexOf("<body>")&&(i="<!DOCTYPE html><body>"+i);var f=a.contentWindow.document;f.open("text/html","replace");f.write(i);f.close();f.body&&(f.body.style.backgroundColor=
"transparent")}catch(l){e.addErrorItem(c,"PermissionDenied")}});return{n:function(){return g()},j:b,h:function(c,a){var d;d=a.id;d='<iframe id="baidu_clb_slot_iframe_'+d+'" src="'+b()+'" onload="BAIDU_DUP_CLB_renderFrame(\''+d+'\')" width="'+a.width+'" height="'+a.height+'" vspace="0" hspace="0" allowTransparency="true" scrolling="no" marginWidth="0" marginHeight="0" frameborder="0" style="border:0; vertical-align:bottom; margin:0; display:block;"></iframe>';c.innerHTML=d}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/logService1418014201",["api"],function(e){var g=o;return{g:function(f){!g&&64!==f.slotType&&(g=m,e.bind(window,"load",function(){window.BAIDU_DUP_require(["clb/detect"],function(){},m)}))}}});
window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/float7o",["api","clb/monitor1418014201","clb/material1418014201","clb/frame1418014201","clb/logService1418014201"],function(e,g,f,b,c){function a(){var b=document.createElement("div"),c=document.createElement("div"),d=o;b.style.position="absolute";b.style.top="200px";c.style.position="fixed";c.style.top="100px";b.appendChild(c);document.body.insertBefore(b,document.body.firstChild);c.getBoundingClientRect&&c.getBoundingClientRect().top!==b.getBoundingClientRect().top&&(d=m);document.body.removeChild(b);
a=function(){return d};return d}function d(a,b){var c=window;c.addEventListener?c.addEventListener(a,b,o):c.attachEvent("on"+a,b,o)}function i(){var a=document.createElement("div");a.innerHTML=q;return a.firstChild}function p(a,b){var c=document.getElementById(b);if(c){var c=c.style,d="CSS1Compat"!==document.compatMode?document.body:document.documentElement,e=d.clientWidth,f=d.clientHeight,g=window.pageXOffset||d.scrollLeft,d=window.pageYOffset||d.scrollTop;c.top=a.f?d+a.c+"px":d+f-a.c-a.height-17+
"px";c.left=a.e?g+a.b+"px":g+e-a.b-a.width+"px"}}function l(h,n){h={id:h.id,data:h._html,i:h._stype,width:h._w,height:h._h,e:h._left,f:h._top,b:h._vs,c:h._hs,d:h._st,scroll:h._sf};c.g(h);g.sendLog(h);if(h.data){if(!n)return null;if(document.body){var j=document.getElementById(n),k=j.style;k.width=h.width+"px";k.height=h.height+17+"px";k.overflow="hidden";k.zIndex=2147483647;var q=h.e?"left":"right",r=h.f?"top":"bottom";k[q]=h.b+"px";k[r]=h.c+"px";h.scroll?a()?k.position="fixed":(k.position="absolute",
p(h,n),d("scroll",function(){p(h,n)}),d("resize",function(){p(h,n)})):(k.position="absolute",k[q]=h.b+"px",k[r]=h.c+"px");document.body.insertBefore(j,document.body.firstChild);k=f.a(h.data,h);e.putInfo("#"+h.id,{html:k});b.h(j,h);k=i();j.appendChild(k);0<h.d&&setTimeout(function(){var a=document.getElementById(n);a&&a.parentNode&&a.parentNode.removeChild(a)},1E3*h.d)}else d("load",function(){l(h,n)})}else e.setStatus(h.id,"finish")}var j="height:15px;,border:1px solid #e1e1e1;,background:#f0f0f0;,margin:0;,padding:0;,overflow:hidden;".split(","),
j=j.join(""),n="float:right;,clear:right;,margin:2px 5px 0 0;,width:39px;,height:13px;,cursor:pointer;,background:url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/clb/1.0.0/close.gif) no-repeat scroll 0 0;".split(","),n=n.join(""),q=['<div style="'+j+'">','<span style="'+n+'" ',"onmouseover=\"this.style.backgroundPosition='0 -20px';\" ","onmouseout=\"this.style.backgroundPosition='0 0';\" ",'onclick="this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode);">',"</span>","</div>"],
q=q.join("");return{render:l,validate:function(a){var b=a._isMlt;return 1!==a._stype||0!==b&&1!==b&&b!==o?o:m}}});
})();window.BAIDU_DUP_define&&window.BAIDU_DUP_define("clb/detect",["api"],function(g){function e(a){a.url="";a.host=window.location.hostname;a.from="DUP";g.sendLog({data:a,a:"now"})}try{setTimeout(function(){var a=g.getSlots(),c;for(c in a){var b=a[c],h=b.status;if(h.render){for(var d=b.errors,i=!1,f=0;f<d.length;f++)if("PermissionDenied"===d[f]){i=!0;break}d=b.response.data&&b.response.data._html;if(i)e({type:"renderFail",id:c,error:"PermissionDenied",empty:!!d});else if(h.finish){if(1!==b.response.data._isMlt&&
(b=document.getElementById("baidu_clb_slot_iframe_"+c)))try{var j=b.contentWindow.document.body;(!j||!j.firstChild)&&e({type:"renderEmpty",id:c})}catch(k){}}else e({type:"renderFail",id:c,error:"NotFilled",empty:!!d})}}},0)}catch(k){}});
