(function(){var r=navigator.userAgent.toLowerCase(),s="&#97;&#98;&#115;&#111;&#108;&#117;&#116;&#101;".replace(/&#([\da-fA-F]{1,5});/g,function(a,b){return String.fromCharCode(b)}),t=r.indexOf("chrome")==-1&&r.indexOf("safari")!=-1,l="",o="";if(typeof _mlR=="undefined"){var e=window._mlR=function(a,b,c,d,f,h){return new e.prototype.init(a,b,c,d,f,h)};e.extend=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a};e.extend(e,{supportFixed:!(window.ActiveXObject&&(document.compatMode==
"BackCompat"||r.match(/msie[ ]([\d.]+)/)[1]<=6)),$:function(a){return typeof a=="string"?document.getElementById(a):a},element:function(a,b,c,d){a=document.createElement(a);if(b)for(var f in b)a.setAttribute(f,b[f]);c&&e.css(a,c);if(d)a.innerHTML=d;return a},swf:function(a,b,c,d,f,h){if(window.ActiveXObject){var g=e.element("span");g.innerHTML='<object id="'+a+'" name="'+a+'" width="'+c+'" height="'+d+'"  classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"><param name="movie" value="'+b+'" /><param name="wmode" value="'+
f+'" /><param name="flashvars" value="'+h+'" /><param name="allowScriptAccess" value="always" /><param name="menu" value="false" /><param name="scale" value="exactfit" /></objcet>';a=g.childNodes[0]}else a=e.element("embed",{id:a,name:a,width:c,height:d,src:b,type:"application/x-shockwave-flash",allowscriptaccess:"always",wmode:f,menu:"false",scale:"exactfit",flashvars:h});return a},img:function(a,b,c,d){return e.element("img",{id:a,border:0,src:b},{width:c+"px",height:d+"px"})},iframe:function(a,
b,c,d){return e.element("iframe",{id:a,width:c,height:d,frameBorder:0,marginwidth:0,marginheight:0,scrolling:"no",src:b})},css:function(a,b){var c=e.$(a);if(typeof b=="string"){if(c.currentStyle)return c.currentStyle[b];if(window.getComputedStyle)return document.defaultView.getComputedStyle(c,null)[b]}else if(typeof b=="object")for(var d in b)c.style[d]=b[d]},getClient:function(a){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();return document.compatMode=="BackCompat"?document.body["client"+
a]:document.documentElement["client"+a]},getScroll:function(a){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();return Math.max(document.documentElement["scroll"+a],document.body["scroll"+a])},getPosition:function(a){for(var a=e.$(a),b=[a.offsetLeft,a.offsetTop],a=a.offsetParent;a;)b[0]+=a.offsetLeft,b[1]+=a.offsetTop,a=a.offsetParent;return b},random:function(a){a=a||0;if(a==-1)for(var b in _a.random)_a.random[b]!=Object.prototype[b]&&(_a.random[b]=null);else return _a.random["_"+a]||(_a.random["_"+
a]=(new Date).getTime()+Math.floor(Math.random()*1E3)),_a.random["_"+a]},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(b){try{a=document.referrer}catch(c){}}return encodeURI(a)},send:function(a,b){var c;b?(c=document.createElement("img"),c.style.display="none"):(c=document.createElement("script"),c.type="text/javascript",c.async=!0);document.body.insertBefore(c,document.body.firstChild);c.src=a+(a.indexOf("?")>0?"&cb=":"?cb=")+Math.ceil(Math.random()*1E9)}});e.prototype={init:function(a,
b,c,d,f,h){this.aid=a;this.mid=b;this.cid=c;this.hrs=d;this.surl=this.info("serverbaseurl")?"http://"+this.info("serverbaseurl"):"http://mlt01.com/";this.purl=e.getPreviousUrl();this.wmode=["opaque","transparent","window"];this.fs=h;this.ts={ct:(new Date).getTime()};this._setState(f);typeof ac_info_ware=="undefined"&&(ac_info_ware={});ac_info_ware["mltag_"+a]=this},setState:function(a){for(var b=this,c=b.fs[b.state-1],d=null,e=0,h=c.length;e<h;e++)c[e][5]===0&&c[e][6]===0?(a!=b.state&&(d=1),e==h-
1?b.heighten(e+1,d,function(){b._setState(a)}):b.heighten(e+1,d)):b._setState(a)},_setState:function(a){if(this.state!=a)this.ts.st=(new Date).getTime(),this.state=a,this.erase(),a>0&&a<=this.fs.length&&this.render()},setSize:function(a,b,c,d,f,h){var g=this,k=["left","right","top","bottom"],f=[f||0,h||0],a=parseInt(a,10)-1,b=parseInt(b,10),c=parseInt(c,10);if(a>=0&&a<g.fs[g.state-1].length){if(d&&d.indexOf("_")!=-1){d=d.toLowerCase();d=d.split("_");for(h=k.length-1;h>=0;h--)g.ys[a].style[k[h]]=null;
for(k=d.length-1;k>=0;k--)g.ys[a].style[d[k]]=f[k]+"px"}g.fs[g.state-1][a][5]==1&&(g.fs[g.state-1][a][7]===0&&e.css(g.xs[a],{left:"-10000px",top:"-10000px"}),e.css(g.xs[a],{width:b+"px",height:c+"px"}));e.css(g.ys[a],{width:b+"px",height:c+"px"});e.css(g.zs[a],{width:b+"px",height:c+"px"});g.cs[a].setAttribute("width",b);g.cs[a].setAttribute("height",c);g.position&&setTimeout(function(){g.position()},0)}},heighten:function(a,b,c){var d=this,f=0,h=0,g=1;a-=1;if(a>=0&&a<d.fs[d.state-1].length)if(f=
parseInt(e.css(d.xs[a],"height"),10),b=b||parseInt(e.css(d.cs[a],"height"),10),f==b)c&&(c(),c=null);else{g=Math.abs(b-f)/(b-f);h=10*g;if(d.xs[a].interval)clearInterval(d.xs[a].interval),d.xs[a].interval=null;d.xs[a].interval=setInterval(function(){f=parseInt(e.css(d.xs[a],"height"),10);f+=h;f*g>=b*g?(e.css(d.xs[a],{height:b+"px"}),clearInterval(d.xs[a].interval),d.xs[a].interval=null,c&&(c(),c=null)):e.css(d.xs[a],{height:f+"px"})},10)}},setPosition:function(){if(!(this.state<0||this.state>this.fs.length))for(var a=
null,b=null,c=e.getClient("width"),d=e.getClient("height"),f=0,h=0,g=e.supportFixed,k=0,m=0,j=0,n=j=f=0,i=0,l=0,p=0,q=a=0,o=this.fs[this.state-1].length;q<o;q++)a=this.fs[this.state-1][q],a[9]=a[9]?a[9]:"0,0,0,0,0,0".split(","),b=this.xs[q].style,f=parseInt(b.width,10),h=parseInt(b.height,10),a[8]==1&&!g&&(k=e.getScroll("left"),m=e.getScroll("top"),e.css(document.body,"position")!="static"&&(k-=document.body.offsetLeft,m-=document.body.offsetTop)),j=a[9][0],n=a[9][1],i=a[9][2]||0,l=a[9][3]||0,p=a[9][4]||
0,a=a[9][5]||0,j=String(j).indexOf("%")!=-1?Math.floor((c-parseInt(f,10))*parseInt(j,10)/100)+k:parseInt(j,10)+k,j+=String(i).indexOf("%")!=-1?Math.floor(c*parseInt(i,10)/100):parseInt(i,10),j+=String(p).indexOf("%")!=-1?Math.floor(f*parseInt(p,10)/100):parseInt(p,10),f=String(n).indexOf("%")!=-1?Math.floor((d-parseInt(h,10))*parseInt(n,10)/100)+m:parseInt(n,10)+m,f+=String(l).indexOf("%")!=-1?Math.floor(d*parseInt(l,10)/100):parseInt(l,10),f+=String(a).indexOf("%")!=-1?Math.floor(h*parseInt(a,10)/
100):parseInt(a,10),b.left=j+"px",b.top=f+"px"},append:function(a){var b=this.info("destid"),c=null,d=null;if(b&&e.$(b))e.$(b).appendChild(a);else if(c=e.$("ml_js01_"+this.aid))(d=c.parentNode)&&d.insertBefore(a,c)},getPageState:function(){var a=["visibilityState","webkitVisibilityState","mozVisibilityState","msVisibilityState"];if(l!="")return document[l];for(var b=0;b<a.length;b++)if(typeof document[a[b]]!="undefined")return l=a[b],document[a[b]];return"visible"},sendViTrack:function(a){var b,c=
this.vts,d="",f=this.fs[this.state-1][a];if(c[a]&&f){b=c[a];b.parentNode.style.display="none";b.parentNode.parentNode.removeChild(b.parentNode);c.splice(a,1);if(typeof f[4]=="object"&&f[4].vu)d=f[4].vu;typeof f[4]=="string"&&/vu='([^"'']+)'/.test(f[4])&&(d=f[4].match(/vu='([^"'']+)'/)[1]);if(d){a=0;for(d=d.split("|||");a<d.length;a++)e.send(d[a],1)}}},pageVisChange:function(){var a=this,b=["visibilityState","webkitVisibilityState","mozVisibilityState","msVisibilityState"],c=["visibilitychange","webkitvisibilitychange",
"mozvisibilitychange","msvisibilitychange"],d="",e="";if(l!=""&&o!="")e=l,d=o;else for(var h=0;h<b.length;h++)if(typeof document[b[h]]!="undefined"){d=c[h];l=e=b[h];o=d;break}if(d!=""&&window.addEventListener)a.visChangeHandler=function(){if(a.vts.length)for(var b=0;b<a.vts.length;b++)try{a.vts[b]&&a.vts[b].setState(document[e])}catch(c){}else document.removeEventListener(d,arguments.callee,!1)},document.addEventListener(d,a.visChangeHandler,!1)},open:function(a){window.ac_info_ware&&ac_info_ware.ts&&
(a=a.replace("[timestamp]",ac_info_ware.ts));window.ActiveXObject?(a=e.element("a",{href:a,target:"_blank"},{display:"none"}),document.body.insertBefore(a,document.body.firstChild),a.click(),a.parentNode.removeChild(a)):window.open(a)},report:function(){},info:function(a,b){typeof ac_info_ware=="undefined"&&(ac_info_ware={});var c="ml"+this.aid;ac_info_ware[c]||(ac_info_ware[c]={});b&&(ac_info_ware[c][a]=b);return ac_info_ware[c][a]},count:function(a){if(!this.es)this.es={};this.es[a]||(this.es[a]=
0);return++this.es[a]},erase:function(){if(this.xs){for(var a=0,b=this.xs.length;a<b;a++){this.xs[a].style.display="none";if(window.ActiveXObject)for(var c in this.cs[a])typeof this.cs[a][c]=="function"&&(this.cs[a][c]=null);this.xs[a].parentNode.removeChild(this.xs[a]);this.cs[a]=null;this.zs[a]=null;this.ys[a]=null;this.xs[a]=null;this.vts[a]=null;this.mcls[a]=null;this.cls[a]=null}if(this.visChangeHandler)this.removeEventListener(o,this.visChangeHandler,!1),this.visChangeHandler=null}if(this.interval)clearInterval(this.interval),
this.interval=null;this.xs=[];this.ys=[];this.zs=[];this.cs=[];this.vts=[];this.mcls=[];this.cls=[]},render:function(){for(var a=this,b=null,c=null,d=null,f=null,h=c=null,g=null,k=null,m=null,j=null,n=null,n=null,g="",i=0,l=a.fs[a.state-1].length;i<l;i++){g=["ac_cs_",a.aid,"_",i+1].join("");b=a.fs[a.state-1][i];h=/swf/i.test(b[0])?e.swf(g,b[0],b[1],b[2],a.wmode[b[3]],a.hrs==1?"cfg="+encodeURIComponent(b[4]):""):/gif|jpg|jpeg|png|bmp/i.test(b[0])?e.img(g,b[0],b[1],b[2],b[4]):e.iframe(g,b[0],b[1],b[2]);
c={overflow:"hidden",position:s,display:"block",width:b[1]+"px",height:b[2]+"px",background:"none",border:0,textAlign:"left"};d=e.element("span",null,c);f=e.element("span",null,c);c=e.element("span",null,c);k=e.element("span",null,{position:"absolute",top:Math.floor(b[2]/2)+"px",left:Math.floor(b[1]/2)+"px",width:"1px",height:"2px",overflow:"hidden",fontSize:0,lineHeight:0});g=e.swf(g+"_v","http://static.mlt01.com/FrameWork/system/vi.swf",t?1:20,t?2:20,t?"transparent":"window","tag=ac_info_ware.mltag_"+
a.aid+"&wt=1000&ci="+i);if(a.hrs===0&&b[4]&&b[4].cu)n=e.element("img",{src:"http://static.mlt01.com/transparent.gif",alt:""},{cursor:"pointer",left:0,top:0,position:s,display:"block",width:b[1]+"px",height:b[2]+"px",border:0}),n.onclick=function(){b[11]||a.report(1,0,0,"i");if(b[4].tu)for(var c=0,d=b[4].tu.split("|||"),f=d.length;c<f;c++)e.send(d[c],1);a.open(b[4].cu)},c.appendChild(n);if(a.hrs===0&&b[7]===0&&b[10]!="")n=e.element("img",{src:b[10],alt:""},{cursor:"pointer",right:0,top:0,position:s,
display:"block",border:0}),n.onclick=function(){a.report(3,0,0,"i");a.erase()},c.appendChild(n);if(b[11]&&b[11].mcl&&b[11].cl)m=e.element("span",null,{position:"absolute",right:0,bottom:0,width:b[11].mcl.w+"px",height:b[11].mcl.h+"px",background:"url("+b[11].mcl.i+") 0 0 no-repeat",overflow:"hidden",fontSize:0,lineHeight:0,zIndex:1,cursor:"pointer"}),j=e.element("span",{title:b[11].cl.tt},{position:"absolute",right:0,bottom:0,width:b[11].cl.w+"px",height:b[11].cl.h+"px",background:"url("+b[11].cl.i+
") 0 0 no-repeat",overflow:"hidden",fontSize:0,lineHeight:0,zIndex:1,cursor:"pointer",display:"none"}),window.XMLHttpRequest||(e.css(m,{background:"none",filter:'progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, src="'+b[11].mcl.i+'", sizingMethod="crop")'}),e.css(j,{background:"none",filter:'progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, src="'+b[11].cl.i+'", sizingMethod="crop")'})),j.onclick=function(){window.open(b[11].cl.cu)},m.onmouseover=function(){var b=m.getAttribute("data-index")*
1;a.mcls[b].style.display="none";a.cls[b].style.display="block"},j.onmouseout=function(){var b=j.getAttribute("data-index")*1;a.mcls[b].style.display="block";a.cls[b].style.display="none"},m.setAttribute("data-index",i),j.setAttribute("data-index",i),a.mcls.push(m),a.cls.push(j),c.appendChild(m),c.appendChild(j);k.appendChild(g);c.appendChild(h);c.appendChild(k);f.appendChild(c);d.appendChild(f);a.cs.push(h);a.vts.push(g);a.zs.push(c);a.ys.push(f);a.xs.push(d);a.append(d,i);b[6]==1?e.css(a.xs[i],
{overflow:"visible"}):e.css(a.xs[i],{overflow:"hidden"});a.position=function(){return a.setPosition.call(a)};if(a.interval)clearInterval(a.interval),a.interval=null;b[7]==1?e.css(a.xs[i],{position:"relative"}):(e.css(a.ys[i],{overflow:"auto"}),e.css(a.xs[i],{zIndex:"2147483647",left:"-1000px",top:"-1000px"}),a.interval=setInterval(function(){a.position()},100),b[8]==1&&e.supportFixed&&e.css(a.xs[i],{position:"fixed"}))}a.pageVisChange()}};e.prototype.init.prototype=e.prototype;_AC_RJS_VERSION_="5.0.7.6"}})();
